import {useEffect,useState} from "react";
import {supabase} from "./lib/supabase";

type Coupon={id:string;code:string;discount_type:string;discount_value:number;usage_limit:number|null;used_count:number;is_active:boolean;starts_at:string|null;expires_at:string|null};
const fmt=(s:string|null)=>s?new Date(s).toLocaleString('ar-EG',{dateStyle:'short',timeStyle:'short'}):'بدون';

export default function AdminCoupons(){
 const [rows,setRows]=useState<Coupon[]>([]),[code,setCode]=useState(''),[type,setType]=useState('percentage'),[value,setValue]=useState('10'),[limit,setLimit]=useState(''),[starts,setStarts]=useState(''),[expires,setExpires]=useState(''),[busy,setBusy]=useState(false),[toast,setToast]=useState<string|null>(null);
 useEffect(()=>{void load()},[]);
 async function load(){setBusy(true);try{const {data,error}=await supabase.from('coupons').select('*').order('created_at',{ascending:false});if(error)return setToast(error.message);setRows((data||[]) as Coupon[])}finally{setBusy(false)}}
 async function add(){if(!code.trim())return setToast('اكتب كود الكوبون');setBusy(true);const {data,error}=await supabase.rpc('admin_create_coupon',{p_code:code.trim(),p_discount_type:type,p_discount_value:Number(value||0),p_usage_limit:limit?Number(limit):null,p_starts_at:starts?new Date(starts).toISOString():null,p_expires_at:expires?new Date(expires).toISOString():null,p_is_active:false});setBusy(false);if(error)return setToast(error.message);if(data)setRows(xs=>[data as Coupon,...xs]);setCode('');setValue('10');setLimit('');setStarts('');setExpires('');setToast('الكوبون اتضاف وهو متوقف افتراضيًا ✓')}
 async function toggle(row:Coupon){const {data,error}=await supabase.rpc('admin_set_coupon_active',{p_id:row.id,p_active:!row.is_active});if(error)return setToast(error.message);if(data)setRows(xs=>xs.map(x=>x.id===row.id?data as Coupon:x));}
 return <section className="admin-coupons" dir="rtl"><div className="psection"><div><span className="pkicker">العروض</span><h2>الكوبونات</h2></div><button className="refresh" onClick={()=>void load()}>تحديث ↻</button></div><div className="coupon-form"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="كود مثل TALBAK10"/><select value={type} onChange={e=>setType(e.target.value)}><option value="percentage">نسبة %</option><option value="fixed">مبلغ ثابت</option></select><input type="number" min="0" value={value} onChange={e=>setValue(e.target.value)} placeholder="قيمة الخصم"/><input type="number" min="1" value={limit} onChange={e=>setLimit(e.target.value)} placeholder="حد الاستخدام (اختياري)"/><input type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)} aria-label="بداية الكوبون"/><input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)} aria-label="انتهاء الكوبون"/><button className="primary" disabled={busy} onClick={()=>void add()}>+ إضافة</button></div><div className="coupon-list">{rows.map(r=><article className={`coupon-card ${r.is_active?'active':''}`} key={r.id}><div><b>{r.code}</b><small>{r.discount_type==='percentage'?`${r.discount_value}% خصم`:`${Math.round(Number(r.discount_value))} ج.م خصم`} • مستخدم {r.used_count}{r.usage_limit?`/${r.usage_limit}`:''}</small><small>من {fmt(r.starts_at)} • إلى {fmt(r.expires_at)}</small></div><div><span>{r.is_active?'🟢 شغال':'⚪ متوقف'}</span><button onClick={()=>void toggle(r)}>{r.is_active?'إيقاف':'تفعيل'}</button></div></article>)}{!rows.length&&<div className="pempty">مفيش كوبونات حاليًا.</div>}</div>{toast&&<div className="toast">{toast}</div>}</section>;
}
