import { useEffect,useMemo,useState } from "react";
import { supabase } from "./lib/supabase";

type Store={id:string;name:string;category:string;description:string;image_url:string|null;address:string;delivery_fee:number;prep_minutes:number;rating:number;is_open:boolean};
type Item={id:string;store_id:string;name:string;description:string;image_url:string|null;price:number;category:string;is_available:boolean};
type Line={item:Item;qty:number};
type Address={id:string;label:string;address_line:string;is_default:boolean};
type Order={id:string;store_id:string;status:string;total:number;subtotal:number;delivery_fee:number;payment_method:string;delivery_address:string;created_at:string;updated_at:string;estimated_minutes:number|null;stores?:{name:string}|null};
const CATS=["الكل","مطاعم","بقالة","مخبوزات","صيدلية","مشروبات","حلويات","عناية","خدمات"];
const IC:Record<string,string>={"الكل":"✨","مطاعم":"🍔","بقالة":"🛒","مخبوزات":"🥐","صيدلية":"💊","مشروبات":"🥤","حلويات":"🍰","عناية":"🧴","خدمات":"📦"};
const ST:Record<string,string>={pending:"بنأكد الطلب",accepted:"المتجر استلم",preparing:"بيجهز طلبك",ready:"جاهز للسائق",assigned:"السائق استلمه",picked_up:"اتستلم من المتجر",on_the_way:"في الطريق ليك",delivered:"اتسلّم بنجاح",cancelled:"اتلغى",rejected:"مرفوض"};
const money=(n:number)=>`${new Intl.NumberFormat("ar-EG").format(Math.round(Number(n)||0))} ج.م`;
const ago=(s:string)=>{const m=Math.max(0,Math.floor((Date.now()-new Date(s).getTime())/60000));return m<1?"دلوقتي":m<60?`من ${m} د`:m<1440?`من ${Math.floor(m/60)} س`:`من ${Math.floor(m/1440)} يوم`};

export default function App(){
 const [tab,setTab]=useState("home"),[stores,setStores]=useState<Store[]>(demoStores),[items,setItems]=useState<Item[]>(demoItems),[query,setQuery]=useState(""),[cat,setCat]=useState("الكل"),[active,setActive]=useState<Store|null>(null),[cart,setCart]=useState<Line[]>([]),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[session,setSession]=useState<any>(null),[profile,setProfile]=useState<any>(null),[orders,setOrders]=useState<Order[]>([]),[addresses,setAddresses]=useState<Address[]>([]),[favorites,setFavorites]=useState<string[]>([]),[notifications,setNotifications]=useState<any[]>([]),[newAddress,setNewAddress]=useState({label:"البيت",address_line:""}),[addressId,setAddressId]=useState<string|null>(null),[note,setNote]=useState(""),[payment,setPayment]=useState<"cash">("cash"),[orderView,setOrderView]=useState<Order|null>(null),[reviewing,setReviewing]=useState<Order|null>(null),[rating,setRating]=useState(5),[comment,setComment]=useState(""),[joinMode,setJoinMode]=useState<"merchant"|"driver"|null>(null),[applicationForm,setApplicationForm]=useState({business_name:"",category:"مطاعم",custom_category:"",address:"",phone:"",full_name:"",vehicle_type:"موتسيكل"}),[toast,setToast]=useState<string|null>(null),[boot,setBoot]=useState(true);
 const selectedAddressId=addressId;
 const openLogin=()=>{window.location.href="/?login=1"}; const openSignup=()=>{window.location.href="/?signup=1"};
 useEffect(()=>{let live=true;supabase.auth.getSession().then(({data})=>{if(!live)return;setSession(data.session);if(data.session)void load(data.session.user.id);else setBoot(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)void load(s.user.id);else setBoot(false)});return()=>{live=false;data.subscription.unsubscribe()}},[]);
 useEffect(()=>{if(!session)return;const uid=session.user.id;const ch=supabase.channel(`cust-${uid}`).on("postgres_changes",{event:"*",schema:"public",table:"orders",filter:`customer_id=eq.${uid}`},()=>void refreshOrders(uid)).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter:`user_id=eq.${uid}`},()=>void refreshNotifications(uid)).subscribe();return()=>{void supabase.removeChannel(ch)}},[session]);
 useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(null),2400);return()=>window.clearTimeout(t)},[toast]);
 async function load(uid:string){const [p,o,a,f,n,s,m]=await Promise.all([supabase.from("profiles").select("*").eq("id",uid).maybeSingle(),supabase.from("orders").select("*,stores(name)").eq("customer_id",uid).order("created_at",{ascending:false}).limit(60),supabase.from("addresses").select("*").eq("user_id",uid).order("is_default",{ascending:false}),supabase.from("favorites").select("store_id").eq("user_id",uid),supabase.from("notifications").select("*").eq("user_id",uid).order("created_at",{ascending:false}).limit(30),supabase.from("stores").select("*").order("rating",{ascending:false}),supabase.from("menu_items").select("*").eq("is_available",true)]);if(p.data)setProfile(p.data);if(o.data)setOrders(o.data);if(a.data){setAddresses(a.data);if(!addressId)setAddressId(a.data.find((x:any)=>x.is_default)?.id||a.data[0]?.id||null)}if(f.data)setFavorites(f.data.map((x:any)=>x.store_id));if(n.data)setNotifications(n.data);if(s.data?.length)setStores(s.data);if(m.data?.length)setItems(m.data);setBoot(false)}
 async function refreshOrders(uid:string){const {data}=await supabase.from("orders").select("*,stores(name)").eq("customer_id",uid).order("created_at",{ascending:false}).limit(60);if(data)setOrders(data)}
 async function refreshNotifications(uid:string){const {data}=await supabase.from("notifications").select("*").eq("user_id",uid).order("created_at",{ascending:false}).limit(30);if(data)setNotifications(data)}
 function addItem(item:Item){if(!item.is_available||!active?.is_open){setToast("الصنف أو المتجر غير متاح دلوقتي");return}if(cart.length&&cart[0].item.store_id!==item.store_id){setToast("السلة لمتجر واحد — فضّي السلة الأول");return}setCart(xs=>{const f=xs.find(x=>x.item.id===item.id);return f?xs.map(x=>x.item.id===item.id?{...x,qty:Math.min(30,x.qty+1)}:x):[...xs,{item,qty:1}]});setToast("اتضاف للسلة ✓")}
 function qty(id:string,d:number){setCart(xs=>xs.map(x=>x.item.id===id?{...x,qty:Math.max(0,Math.min(30,x.qty+d))}:x).filter(x=>x.qty>0))}
 async function place(){if(!session){openLogin();return}if(!cart.length)return;if(!selectedAddressId){setTab("profile");setCartOpen(false);return setToast("اختار أو أضف عنوان توصيل الأول")};const store=stores.find(s=>s.id===cart[0].item.store_id);if(!store)return;const {data,error}=await supabase.rpc("create_order_secure",{p_store_id:store.id,p_items:cart.map(x=>({menu_item_id:x.item.id,quantity:x.qty})),p_address:addresses.find(a=>a.id===selectedAddressId)?.address_line||"",p_payment_method:"cash",p_note:note});if(error)return setToast(error.message);if(data)setOrders(xs=>[data,...xs]);setCart([]);setCheckout(false);setCartOpen(false);setTab("orders");setToast("طلبك اتسجل بنجاح 🎉")}
 async function saveAddress(){if(!session)return openLogin();if(!newAddress.address_line.trim())return setToast("اكتب العنوان");const first=addresses.length===0;const {data,error}=await supabase.from("addresses").insert({user_id:session.user.id,label:newAddress.label.trim()||"العنوان",address_line:newAddress.address_line.trim(),is_default:first}).select().single();if(error)return setToast(error.message);setAddresses(xs=>[...xs,data]);setAddressId(data.id);setNewAddress({label:"البيت",address_line:""});setToast("العنوان اتضاف ✓")}
 async function defaultAddress(a:Address){if(!session)return;const {error:e1}=await supabase.from("addresses").update({is_default:false}).eq("user_id",session.user.id);if(e1)return setToast(e1.message);const {error}=await supabase.from("addresses").update({is_default:true}).eq("id",a.id).eq("user_id",session.user.id);if(error)return setToast(error.message);setAddresses(xs=>xs.map(x=>({...x,is_default:x.id===a.id})));setAddressId(a.id)}
 async function fav(id:string){if(!session)return openLogin();if(favorites.includes(id)){const {error}=await supabase.from("favorites").delete().eq("user_id",session.user.id).eq("store_id",id);if(error)return setToast(error.message);setFavorites(xs=>xs.filter(x=>x!==id))}else{const {error}=await supabase.from("favorites").insert({user_id:session.user.id,store_id:id});if(error)return setToast(error.message);setFavorites(xs=>[...xs,id])}}
 async function cancel(o:Order){const {error}=await supabase.rpc("customer_cancel_order",{p_order_id:o.id});if(error)return setToast(error.message);setOrders(xs=>xs.map(x=>x.id===o.id?{...x,status:"cancelled"}:x));setToast("الطلب اتلغى ✓")}
 async function sendReview(){if(!reviewing||rating<1||rating>5)return;const {error}=await supabase.rpc("submit_store_review",{p_order_id:reviewing.id,p_rating:rating,p_comment:comment.trim()});if(error)return setToast(error.message);setReviewing(null);setComment("");setRating(5);setToast("التقييم اتبعت ✓")}
 async function submitApplication(){if(joinMode==="merchant"&&!applicationForm.business_name.trim()&&!applicationForm.address.trim())return setToast("اكمل بيانات النشاط");if(joinMode==="driver"&&!applicationForm.full_name.trim())return setToast("اكتب اسمك");const {error}=await supabase.rpc(joinMode==="merchant"?"submit_merchant_application":"submit_driver_application",joinMode==="merchant"?{p_business_name:applicationForm.business_name.trim(),p_category:applicationForm.category,p_custom_category:applicationForm.custom_category.trim(),p_address:applicationForm.address.trim(),p_phone:applicationForm.phone.trim()}:{p_full_name:applicationForm.full_name.trim(),p_phone:applicationForm.phone.trim(),p_vehicle_type:applicationForm.vehicle_type});if(error)return setToast(error.message);setJoinMode(null);setToast("طلبك اتبعت ✓")}
 const filtered=useMemo(()=>stores.filter(s=>(cat==="الكل"||s.category===cat)&&`${s.name} ${s.category} ${s.description}`.toLowerCase().includes(query.toLowerCase())),[stores,cat,query]);
 const cartStore=cart.length?stores.find(s=>s.id===cart[0].item.store_id):null; const count=cart.reduce((a,x)=>a+x.qty,0); const subtotal=cart.reduce((a,x)=>a+Number(x.item.price)*x.qty,0); const delivery=cartStore?Number(cartStore.delivery_fee):0; const total=subtotal+delivery;
 if(boot)return <div className="splash">جاري تجهيز طلبك…</div>;
 return <div className="app" dir="rtl">{...CONTENT_OMITTED_FOR_DIFF...}</div>;
}
