import { useEffect, useMemo, useState } from "react";
import { supabase } from "./lib/supabase";

type Store={id:string;name:string;category:string;description:string;image_url?:string|null;address:string;delivery_fee:number;is_open:boolean;prep_minutes:number;rating:number};
type Item={id:string;store_id:string;name:string;description:string;image_url?:string|null;price:number;category:string;is_available:boolean};
type Line={item:Item;qty:number};
type Order={id:string;store_id:string;storeName?:string;status:string;subtotal:number;delivery_fee:number;total:number;payment_method:string;delivery_address:string;created_at:string;estimated_minutes?:number|null};
const cats=["الكل","مطاعم","بقالة","مخبوزات","صيدلية","مشروبات","حلويات","عناية","خدمات"];
const catIcon:Record<string,string>={"الكل":"✨","مطاعم":"🍔","بقالة":"🛒","مخبوزات":"🥐","صيدلية":"💊","مشروبات":"🥤","حلويات":"🍰","عناية":"🧴","خدمات":"📦"};
const stores0:Store[]=[
{id:"demo-1",name:"برجر هب",category:"مطاعم",description:"برجر طازة • وجبات كومبو • تحضير سريع",image_url:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80",address:"مدينة نصر",delivery_fee:15,is_open:true,prep_minutes:18,rating:4.8},
{id:"demo-2",name:"سوبر ماركت النخبة",category:"بقالة",description:"كل احتياجات البيت في طلب واحد",image_url:"https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",address:"المعادي",delivery_fee:20,is_open:true,prep_minutes:10,rating:4.7},
{id:"demo-3",name:"بريد & بريك",category:"مخبوزات",description:"مخبوزات وفطار وحلويات يومية",image_url:"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80",address:"التجمع",delivery_fee:12,is_open:true,prep_minutes:14,rating:4.9},
{id:"demo-4",name:"ركن القهوة",category:"مشروبات",description:"قهوة مختصة ومشروبات باردة",image_url:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",address:"مصر الجديدة",delivery_fee:12,is_open:false,prep_minutes:12,rating:4.6},
{id:"demo-5",name:"صيدلية الحياة",category:"صيدلية",description:"مستلزمات يومية ومنتجات عناية",image_url:"https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=900&q=80",address:"الرحاب",delivery_fee:18,is_open:true,prep_minutes:8,rating:4.8},
{id:"demo-6",name:"سكر زيادة",category:"حلويات",description:"كيك • كوكيز • حلويات للمناسبات",image_url:"https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=80",address:"مصر الجديدة",delivery_fee:16,is_open:true,prep_minutes:20,rating:4.9}
];
const items0:Item[]=[
{id:"i1",store_id:"demo-1",name:"سماش برجر كلاسيك",description:"قطعتين لحم • جبنة • صوص البيت",price:145,category:"برجر",is_available:true,image_url:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=600&q=80"},
{id:"i2",store_id:"demo-1",name:"تشيكن كرسبي",description:"دجاج مقرمش • جبنة • صوص",price:125,category:"برجر",is_available:true,image_url:"https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=600&q=80"},
{id:"i3",store_id:"demo-1",name:"بطاطس تشيدر",description:"بطاطس مقرمشة مع تشيدر",price:75,category:"جانبي",is_available:true,image_url:"https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?auto=format&fit=crop&w=600&q=80"},
{id:"i4",store_id:"demo-2",name:"باكدج أسبوع البيت",description:"اختيارات أساسية موفرة",price:420,category:"عروض",is_available:true,image_url:"https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=600&q=80"},
{id:"i5",store_id:"demo-3",name:"كرواسون زبدة",description:"مخبوز طازة يوميًا",price:55,category:"مخبوزات",is_available:true,image_url:"https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80"},
{id:"i6",store_id:"demo-4",name:"آيس لاتيه",description:"إسبريسو • حليب • ثلج",price:85,category:"قهوة",is_available:true,image_url:"https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80"},
{id:"i7",store_id:"demo-5",name:"مجموعة عناية يومية",description:"غسول + مرطب + واقي شمس",price:295,category:"عناية",is_available:true,image_url:"https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=600&q=80"},
{id:"i8",store_id:"demo-6",name:"كوكيز شوكولاتة",description:"كوكيز طرية محشية شوكولاتة",price:85,category:"حلويات",is_available:true,image_url:"https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80"}
];
function money(n:number){return `${new Intl.NumberFormat("ar-EG").format(Math.round(n))} ج.م`}
function since(s:string){const m=Math.max(0,Math.floor((Date.now()-new Date(s).getTime())/60000));if(m<1)return "دلوقتي";if(m<60)return `من ${m} د`;const h=Math.floor(m/60);if(h<24)return `من ${h} س`;return `من ${Math.floor(h/24)} يوم`}
function status(s:string){return ({pending:"جاري التأكيد",accepted:"المتجر استلم",preparing:"جاري التجهيز",ready:"جاهز",assigned:"تم تعيين سائق",picked_up:"السائق استلم",on_the_way:"في الطريق",delivered:"تم التوصيل",cancelled:"تم الإلغاء",rejected:"مرفوض"} as Record<string,string>)[s]||"جاري المتابعة"}
export default function App(){
const [stores,setStores]=useState<Store[]>(stores0),[items,setItems]=useState<Item[]>(items0),[tab,setTab]=useState("home"),[query,setQuery]=useState(""),[cat,setCat]=useState("الكل"),[active,setActive]=useState<Store|null>(null),[cart,setCart]=useState<Line[]>([]),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[authOpen,setAuthOpen]=useState(false),[authMode,setAuthMode]=useState<"login"|"signup">("login"),[session,setSession]=useState<any>(null),[profile,setProfile]=useState<any>(null),[orders,setOrders]=useState<Order[]>([]),[favorites,setFavorites]=useState<string[]>([]),[notifs,setNotifs]=useState<any[]>([]),[toast,setToast]=useState<string|null>(null),[address,setAddress]=useState(""),[note,setNote]=useState(""),[payment,setPayment]=useState("cash"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState("");
useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(!session)return;const uid=session.user.id;(async()=>{const [p,o,f,n,s,i]=await Promise.all([supabase.from("profiles").select("*").eq("id",uid).maybeSingle(),supabase.from("orders").select("*,stores(name)").eq("customer_id",uid).order("created_at",{ascending:false}).limit(30),supabase.from("favorites").select("store_id").eq("user_id",uid),supabase.from("notifications").select("*").eq("user_id",uid).order("created_at",{ascending:false}).limit(30),supabase.from("stores").select("*").order("rating",{ascending:false}),supabase.from("menu_items").select("*").eq("is_available",true)]);if(p.data)setProfile(p.data);if(o.data)setOrders(o.data.map((x:any)=>({...x,storeName:x.stores?.name})));if(f.data)setFavorites(f.data.map((x:any)=>x.store_id));if(n.data)setNotifs(n.data);if(s.data?.length)setStores(s.data);if(i.data?.length)setItems(i.data)})()},[session]);
useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(null),2500);return()=>clearTimeout(t)}},[toast]);
const filtered=useMemo(()=>stores.filter(s=>(cat==="الكل"||s.category===cat)&&(!query||`${s.name} ${s.description} ${s.category}`.toLowerCase().includes(query.toLowerCase()))),[stores,cat,query]);
const menu=useMemo(()=>active?items.filter(i=>i.store_id===active.id&&i.is_available):[],[items,active]);
const cartCount=cart.reduce((a,l)=>a+l.qty,0),subtotal=cart.reduce((a,l)=>a+l.qty*Number(l.item.price),0),cartStore=cart[0]?stores.find(s=>s.id===cart[0].item.store_id):null,delivery=cartStore?.delivery_fee||0,total=subtotal+delivery,unread=notifs.filter(n=>!n.is_read).length;
function add(item:Item){if(cart.length&&cart[0].item.store_id!==item.store_id){setToast("السلة لمتجر واحد — فضّي السلة الأول");return}setCart(x=>{const f=x.find(v=>v.item.id===item.id);return f?x.map(v=>v.item.id===item.id?{...v,qty:v.qty+1}:v):[...x,{item,qty:1}]});setToast("اتضاف للسلة ✓")}
function qty(id:string,d:number){setCart(x=>x.map(v=>v.item.id===id?{...v,qty:v.qty+d}:v).filter(v=>v.qty>0))}
async function auth(){if(!email||password.length<6){setToast("اكتب إيميل صحيح وكلمة سر 6 أحرف على الأقل");return}const r=authMode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error){setToast(r.error.message);return}if(authMode==="signup"&&r.data.user)await supabase.from("profiles").upsert({id:r.data.user.id,full_name:name||"مستخدم طلبك",phone:phone||null});setAuthOpen(false);setToast(authMode==="login"?"أهلاً بيك 👋":"تم إنشاء الحساب");}
async function place(){if(!session){setAuthOpen(true);setToast("سجّل دخول عشان نثبت الطلب");return}if(!address.trim()){setToast("اكتب عنوان التوصيل");return}const sid=cart[0].item.store_id;const {data,error}=await supabase.from("orders").insert({customer_id:session.user.id,store_id:sid,status:"pending",subtotal,delivery_fee:delivery,total,payment_method:payment,delivery_address:address.trim(),customer_note:note.trim(),estimated_minutes:(cartStore?.prep_minutes||20)+20}).select("*,stores(name)").single();if(error){setToast(error.message);return}const er=await supabase.from("order_items").insert(cart.map(l=>({order_id:data.id,menu_item_id:l.item.id,name_snapshot:l.item.name,unit_price:l.item.price,quantity:l.qty,line_total:l.item.price*l.qty})));if(er.error){setToast("تم الطلب لكن تفاصيل السلة لم تُحفظ بالكامل");return}setOrders(x=>[{...data,storeName:data.stores?.name},...x]);setCart([]);setCheckout(false);setCartOpen(false);setTab("orders");setToast("طلبك اتسجل بنجاح 🎉")}
async function fav(id:string){if(!session){setAuthOpen(true);return}if(favorites.includes(id)){await supabase.from("favorites").delete().eq("user_id",session.user.id).eq("store_id",id);setFavorites(x=>x.filter(v=>v!==id))}else{await supabase.from("favorites").insert({user_id:session.user.id,store_id:id});setFavorites(x=>[...x,id])}}
async function read(){if(!session||!unread)return;await supabase.from("notifications").update({is_read:true}).eq("user_id",session.user.id).eq("is_read",false);setNotifs(x=>x.map(n=>({...n,is_read:true})))}
const trackIndex=(s:string)=>["pending","accepted","preparing","ready","assigned","picked_up","on_the_way","delivered"].indexOf(s);
return <div className="app" dir="rtl">
<header><div className="brand" onClick={()=>setTab("home")}><span className="logo">ط</span><div><b>طلبك</b><small>دليفري</small></div></div><div className="actions"><button onClick={()=>setToast("إضافة العنوان والخرائط الذكية متاحة من ملفك")}>⌖</button><button onClick={()=>{setTab("profile");read()}}>🔔{unread>0&&<i>{unread}</i>}</button><button className="avatar" onClick={()=>setTab("profile")}>{(profile?.full_name||"ز").slice(0,1)}</button></div></header>
{tab==="home"&&<main className="page"><section className="hero"><div><span className="kicker lime">طلبك في طريقه ليك</span><h1>الأكل، البيت، <em>وأي حاجة</em>… في طلب واحد.</h1><p>اختار من أقرب متجر، اطلب في كام خطوة، وتابع الرحلة لحد باب البيت.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="مطعم، أكلة، منتج…"/>{query&&<button onClick={()=>setQuery("")}>×</button>}</div><div className="trust"><span>⚡ سريع</span><span>🛡️ آمن</span><span>💵 كاش</span></div></div><div className="hero-art"><div className="glow one"/><div className="glow two"/><div className="promo"><small>🔥 الأكثر طلبًا</small><b>سماش برجر + بطاطس</b><span>من 145 ج.م • حوالي 30 دقيقة</span><div><i/></div></div></div></section>
<section className="section"><div className="section-head"><div><span className="kicker">استكشف</span><h2>إيه نفسك فيه؟</h2></div><button onClick={()=>setCat("الكل")}>كل الأقسام</button></div><div className="chips">{cats.map(c=><button className={cat===c?"active":""} key={c} onClick={()=>setCat(c)}><span>{catIcon[c]}</span>{c}</button>)}</div></section>
<section className="section"><div className="section-head"><div><span className="kicker">مختارات قريبة</span><h2>{cat==="الكل"?"أماكن تستاهل التجربة":cat}</h2></div><small>{filtered.length} مكان</small></div><div className="grid">{filtered.map(s=><article className="store" key={s.id} onClick={()=>setActive(s)}><div className="media">{s.image_url?<img src={s.image_url} alt=""/>:<div className="fallback">{s.name[0]}</div>}<button className={`heart ${favorites.includes(s.id)?"on":""}`} onClick={e=>{e.stopPropagation();fav(s.id)}}>{favorites.includes(s.id)?"♥":"♡"}</button><span>{s.is_open?"مفتوح":"مغلق"}</span></div><div className="store-copy"><div><h3>{s.name}</h3><b>★ {Number(s.rating||0).toFixed(1)}</b></div><p>{s.description}</p><small>{s.category} <i>•</i> {s.prep_minutes+20}–{s.prep_minutes+30} د <i>•</i> {money(s.delivery_fee)} توصيل</small></div></article>)}</div></section>
<section className="partner"><div><span className="kicker">لأصحاب المتاجر</span><h2>خلّي طلبك يشتغل معاك، مش ضدك.</h2><p>استقبل الطلبات، حدّث الأصناف، راقب التشغيل والمبيعات، وسيب التوصيل علينا.</p><button onClick={()=>setToast("بوابة الشركاء مرتبطة بنفس حساب المنصة")}>انضم كشريك ←</button></div><div className="numbers"><div><b>24/7</b><span>متابعة</span></div><div><b>كل حاجة</b><span>مكان واحد</span></div></div></section>
</main>}
{tab==="orders"&&<main className="page inner"><div className="title"><div><span className="kicker">رحلة طلباتك</span><h1>طلباتي</h1></div><button className="outline" onClick={()=>setTab("home")}>+ طلب جديد</button></div>{!session&&<div className="login-cta"><div><b>خلي طلباتك معاك دايمًا</b><p>سجّل دخول عشان تحفظ الطلبات وتتابعها.</p></div><button onClick={()=>setAuthOpen(true)}>تسجيل الدخول</button></div>}{session&&orders.map(o=><article className="order" key={o.id}><div className="order-head"><div><small>طلب #{o.id.slice(0,6).toUpperCase()} • {since(o.created_at)}</small><h3>{o.storeName||stores.find(s=>s.id===o.store_id)?.name||"متجر"}</h3></div><span>{status(o.status)}</span></div><div className="steps">{["استلام","تجهيز","سائق","طريق","تم"].map((x,i)=><div className={trackIndex(o.status)>=Math.max(0,i*2)?"done":""} key={x}><i>{i===4?"✓":"•"}</i><small>{x}</small></div>)}</div><div className="order-foot"><span>{o.delivery_address}</span><b>{money(Number(o.total))}</b><button onClick={()=>setToast("تفاصيل الطلب وإعادة الطلب متاحين من داخل البطاقة")}>تفاصيل</button></div></article>)}{session&&!orders.length&&<div className="empty"><div>🛍️</div><h3>لسه مفيش طلبات</h3><p>ابدأ أول طلب وهتلاقي الرحلة كلها هنا.</p><button onClick={()=>setTab("home")}>ابدأ دلوقتي</button></div>}</main>}
{tab==="saved"&&<main className="page inner"><div className="title"><div><span className="kicker">أماكنك المفضلة</span><h1>المفضلة</h1></div></div>{favorites.length?<div className="grid">{stores.filter(s=>favorites.includes(s.id)).map(s=><article className="store" key={s.id} onClick={()=>setActive(s)}><div className="media">{s.image_url&&<img src={s.image_url} alt=""/>}<button className="heart on" onClick={e=>{e.stopPropagation();fav(s.id)}}>♥</button></div><div className="store-copy"><div><h3>{s.name}</h3><b>★ {Number(s.rating).toFixed(1)}</b></div><p>{s.description}</p><small>{s.category} <i>•</i> {money(s.delivery_fee)} توصيل</small></div></article>)}</div>:<div className="empty"><div>♡</div><h3>المفضلة فاضية</h3><p>اضغط القلب على أي متجر وهتلاقيه هنا.</p><button onClick={()=>setTab("home")}>استكشف المتاجر</button></div>}</main>}
{tab==="profile"&&<main className="page inner"><section className="profile"><div className="pavatar">{(profile?.full_name||"ز").slice(0,1)}</div><div><span className="kicker lime">حسابك</span><h1>{session?(profile?.full_name||"مستخدم طلبك"):"ضيف"}</h1><p>{session?(profile?.phone||session.user.email):"سجّل الدخول عشان تفتح كل المميزات"}</p></div>{session?<button onClick={async()=>{await supabase.auth.signOut();setProfile(null);setOrders([]);}}>خروج</button>:<button onClick={()=>setAuthOpen(true)}>تسجيل الدخول</button>}</section><div className="profile-grid"><button><span>📍</span><div><b>عناويني</b><small>إدارة أماكن التوصيل</small></div>←</button><button onClick={read}><span>🔔</span><div><b>الإشعارات</b><small>{unread?`${unread} جديد`:"مفيش جديد"}</small></div>←</button><button><span>🎁</span><div><b>المكافآت</b><small>النقاط والعروض</small></div>←</button><button><span>🛟</span><div><b>المساعدة</b><small>دعم ومشاكل الطلب</small></div>←</button></div><section className="notifications"><div className="section-head"><div><span className="kicker">آخر التنبيهات</span><h2>الإشعارات</h2></div></div>{notifs.length?notifs.slice(0,6).map(n=><div className={n.is_read?"note":"note new"} key={n.id}><span>●</span><div><b>{n.title}</b><p>{n.body}</p><small>{since(n.created_at)}</small></div></div>):<div className="muted">مفيش إشعارات لحد دلوقتي.</div>}</section></main>}
<nav className="nav"><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}><b>⌂</b>الرئيسية</button><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}><b>▣</b>طلباتي</button><button className="cart" onClick={()=>setCartOpen(true)}>🛒{cartCount>0&&<i>{cartCount}</i>}</button><button className={tab==="saved"?"active":""} onClick={()=>setTab("saved")}><b>♡</b>المفضلة</button><button className={tab==="profile"?"active":""} onClick={()=>setTab("profile")}><b>◯</b>حسابي</button></nav>
{active&&<div className="shade" onClick={()=>setActive(null)}><div className="store-modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setActive(null)}>×</button><div className="cover">{active.image_url&&<img src={active.image_url} alt=""/>}</div><div className="modal-body"><div className="modal-title"><div><span className="open">{active.is_open?"مفتوح الآن":"مغلق الآن"}</span><h2>{active.name}</h2><p>{active.description}</p></div><button className={`heart big ${favorites.includes(active.id)?"on":""}`} onClick={()=>fav(active.id)}>{favorites.includes(active.id)?"♥":"♡"}</button></div><div className="meta">★ {Number(active.rating).toFixed(1)} <i>•</i> {active.prep_minutes+20}–{active.prep_minutes+30} دقيقة <i>•</i> {money(active.delivery_fee)} توصيل</div><div className="menu">{menu.length?menu.map(it=><div className="item" key={it.id}><div className="item-img">{it.image_url&&<img src={it.image_url} alt=""/>}</div><div><b>{it.name}</b><p>{it.description}</p><strong>{money(Number(it.price))}</strong></div><button onClick={()=>add(it)}>+</button></div>):<div className="muted">الأصناف هتظهر هنا بمجرد إضافتها.</div>}</div></div></div></div>}
{cartOpen&&<div className="shade" onClick={()=>setCartOpen(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="kicker">جاهز؟</span><h2>سلتك</h2></div><button className="x" onClick={()=>setCartOpen(false)}>×</button></div>{cart.length?<><div className="cart-store"><b>{cartStore?.name}</b><small>{cartCount} منتج</small></div>{cart.map(l=><div className="line" key={l.item.id}><img src={l.item.image_url||""}/><div><b>{l.item.name}</b><small>{money(Number(l.item.price))}</small></div><div className="counter"><button onClick={()=>qty(l.item.id,-1)}>−</button><b>{l.qty}</b><button onClick={()=>qty(l.item.id,1)}>+</button></div></div>)}<div className="sum"><div><span>الإجمالي الفرعي</span><b>{money(subtotal)}</b></div><div><span>التوصيل</span><b>{money(delivery)}</b></div><div className="grand"><span>الإجمالي</span><b>{money(total)}</b></div></div><button className="primary full" onClick={()=>setCheckout(true)}>إتمام الطلب</button></>:<div className="empty"><div>🛒</div><h3>السلة فاضية</h3><p>ضيف أول منتج عشان تبدأ.</p></div>}{checkout&&<div className="checkout"><div className="drawer-head"><div><span className="kicker">آخر خطوة</span><h2>تأكيد الطلب</h2></div><button className="x" onClick={()=>setCheckout(false)}>×</button></div><label>عنوان التوصيل<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="مثال: عباس العقاد، مدينة نصر"/></label><label>ملاحظات<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="الدور، علامة مميزة، تعليمات للسائق..."/></label><div className="payments"><button className={payment==="cash"?"selected":""} onClick={()=>setPayment("cash")}>💵<b>كاش</b><small>عند الاستلام</small></button><button className={payment==="online"?"selected":""} onClick={()=>setPayment("online")}>💳<b>إلكتروني</b><small>جاهز للربط</small></button></div><button className="primary full" onClick={place}>تأكيد الطلب • {money(total)}</button></div>}</aside></div>}
{authOpen&&<div className="shade" onClick={()=>setAuthOpen(false)}><div className="auth" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setAuthOpen(false)}>×</button><span className="auth-logo">ط</span><span className="kicker">{authMode==="login"?"رجوعك يسعدنا":"أهلاً بيك"}</span><h2>{authMode==="login"?"سجّل دخولك":"اعمل حساب جديد"}</h2><p>{authMode==="login"?"احفظ طلباتك ومفضلاتك وتابعها بسهولة.":"دقيقة واحدة وتكون جاهز لأول طلب."}</p>{authMode==="signup"&&<><input value={name} onChange={e=>setName(e.target.value)} placeholder="الاسم بالكامل"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="رقم الموبايل"/></>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="البريد الإلكتروني"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="كلمة السر"/><button className="primary full" onClick={auth}>{authMode==="login"?"دخول":"إنشاء الحساب"}</button><button className="switch" onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"لسه معندكش حساب؟ اعمل حساب":"عندك حساب بالفعل؟ سجّل دخول"}</button></div></div>}
{toast&&<div className="toast">{toast}</div>}</div>}
''