import React,{useEffect,useState} from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import Portal from "./Portal";
import AuthOnboarding from "./AuthOnboarding";
import "./index.css";
import { supabase } from "./lib/supabase";

type Role="merchant"|"driver"|"admin";
const roleLabel:Record<Role,string>={admin:"الإدارة",merchant:"التاجر",driver:"السائق"};
function Logo({size=76}:{size?:number}){return <img src="/logo.svg" alt="طلبك دليفري" style={{width:size,height:size,objectFit:"contain",display:"block",margin:"0 auto"}}/>}
function RoleChooser({roles,onPick}:{roles:Role[];onPick:(r:Role)=>void}){return <div className="boot" dir="rtl"><div style={{maxWidth:520,width:"92%",background:"white",padding:28,borderRadius:24,boxShadow:"0 20px 60px rgba(0,0,0,.12)",textAlign:"center"}}><Logo size={76}/><h1 style={{margin:"12px 0 6px",color:"#173b22"}}>اختار مركز العمل</h1><p>نفس الحساب عنده أكتر من دور. اختار المكان اللي عايز تستخدمه دلوقتي.</p><div style={{display:"grid",gap:12,marginTop:20}}>{roles.map(r=><button key={r} onClick={()=>onPick(r)} style={{padding:"16px 18px",borderRadius:16,border:"1px solid #dce8df",background:"#fff",color:"#173b22",fontSize:17,cursor:"pointer",fontWeight:800}}>{roleLabel[r]}</button>)}</div><button onClick={()=>{window.location.href="/?customer=1"}} style={{marginTop:12,padding:12,border:0,background:"transparent",color:"#4b961a",cursor:"pointer",fontWeight:800}}>استكشف واجهة العميل</button></div></div>}
class AppErrorBoundary extends React.Component<{children:React.ReactNode},{hasError:boolean}>{state={hasError:false};static getDerivedStateFromError(){return {hasError:true}};componentDidCatch(error:Error){console.error("Talbak UI error",error)};render(){if(this.state.hasError)return <div className="boot" dir="rtl"><Logo size={64}/><h2>حصل خطأ في واجهة التطبيق</h2><p>جرّب تحديث الصفحة. لو المشكلة مستمرة، نقدر نراجعها من سجل التشغيل.</p><button onClick={()=>location.reload()} style={{padding:"12px 18px",border:0,borderRadius:12,cursor:"pointer"}}>تحديث التطبيق</button></div>;return this.props.children}}
function Root(){const [roles,setRoles]=useState<Role[]>([]),[session,setSession]=useState<any>(null),[checked,setChecked]=useState(false);useEffect(()=>{let alive=true;(async()=>{const {data}=await supabase.auth.getSession();if(!alive)return;setSession(data.session);if(data.session){const {data:r}=await supabase.from("user_roles").select("role").eq("user_id",data.session.user.id);setRoles(((r||[]).map((x:any)=>x.role).filter((x:any)=>x==="admin"||x==="merchant"||x==="driver") as Role[]))}setChecked(true)})();const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>{alive=false;data.subscription.unsubscribe()};},[]);useEffect(()=>{if("serviceWorker" in navigator)void navigator.serviceWorker.register("/sw.js")},[]);if(!checked)return <div className="boot"><Logo size={64}/><div style={{marginTop:8}}>جاري تشغيل طلبك…</div></div>;const params=new URLSearchParams(location.search);if(!session){if(params.get("signup")==="1"||params.get("login")==="1")return <AuthOnboarding/>;if(params.get("customer")==="1")return <App/>;return <AuthOnboarding/>}if(params.get("customer")==="1")return <App/>;const requested=params.get("role") as Role|null;const validRequested=requested&&roles.includes(requested)?requested:null;if(validRequested)return <Portal role={validRequested}/>;if(roles.includes("admin"))return <Portal role="admin"/>;if(roles.length===1)return <Portal role={roles[0]}/>;if(roles.length>1)return <RoleChooser roles={roles} onPick={r=>{location.href=`/?role=${r}`}}/>;return <App/>}
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><AppErrorBoundary><Root/></AppErrorBoundary></React.StrictMode>);