import React,{useEffect,useState} from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import Portal from "./Portal";
import AuthOnboarding from "./AuthOnboarding";
import SupportCenter from "./SupportCenter";
import WorkspaceShell from "./WorkspaceShell";
import "./index.css";
import { supabase } from "./lib/supabase";

type Role="customer"|"merchant"|"driver"|"admin";
const roleLabel:Record<Role,string>={customer:"العميل",admin:"الإدارة",merchant:"التاجر",driver:"السائق"};
function Logo({size=76}:{size?:number}){return <img src="/logo.svg" alt="طلبك دليفري" style={{width:size,height:size,objectFit:"contain",display:"block",margin:"0 auto"}}/>}
function RoleChooser({roles,onPick}:{roles:Role[];onPick:(r:Role)=>void}){return <WorkspaceShell role={roles.includes("customer")?"customer":roles[0]}><div className="boot" dir="rtl"><div style={{maxWidth:520,width:"92%",background:"white",padding:28,borderRadius:24,boxShadow:"0 20px 60px rgba(0,0,0,.12)",textAlign:"center"}}><Logo size={76}/><h1 style={{margin:"12px 0 6px",color:"#173b22"}}>اختار واجهتك</h1><p>الحساب نفسه يحتفظ بكل أدوارك. كل اختيار يفتح واجهة مستقلة بالكامل بصلاحياتها ووظائفها.</p><div style={{display:"grid",gap:12,marginTop:20}}>{roles.map(r=><button key={r} onClick={()=>onPick(r)} style={{padding:"16px 18px",borderRadius:16,border:"1px solid #dce8df",background:"#fff",color:"#173b22",fontSize:17,cursor:"pointer",fontWeight:800}}>{roleLabel[r]}</button>)}</div></div></div></WorkspaceShell>}
class AppErrorBoundary extends React.Component<{children:React.ReactNode},{hasError:boolean}>{state={hasError:false};static getDerivedStateFromError(){return {hasError:true}};componentDidCatch(error:Error){console.error("Talbak UI error",error)};render(){if(this.state.hasError)return <div className="boot" dir="rtl"><Logo size={64}/><h2>حصل خطأ في واجهة التطبيق</h2><p>جرّب تحديث الصفحة. لو المشكلة مستمرة، نقدر نراجعها من سجل التشغيل.</p><button onClick={()=>location.reload()} style={{padding:"12px 18px",border:0,borderRadius:12,cursor:"pointer"}}>تحديث التطبيق</button></div>;return this.props.children}}
function LivePortal({role}:{role:Exclude<Role,"customer">}){const [version,setVersion]=useState(0);useEffect(()=>{let timer:number|undefined;const bump=()=>{if(timer)window.clearTimeout(timer);timer=window.setTimeout(()=>setVersion(v=>v+1),250)};let cleanup=()=>{};void supabase.auth.getUser().then(({data})=>{const uid=data.user?.id;if(!uid)return;let channel=supabase.channel(`portal-live-${role}-${uid}`).on("postgres_changes",{event:"*",schema:"public",table:"orders"},bump).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter:`user_id=eq.${uid}`},bump).on("postgres_changes",{event:"*",schema:"public",table:"driver_status",filter:`user_id=eq.${uid}`},bump);if(role==="admin")channel=channel.on("postgres_changes",{event:"*",schema:"public",table:"merchant_applications"},bump).on("postgres_changes",{event:"*",schema:"public",table:"driver_applications"},bump).on("postgres_changes",{event:"*",schema:"public",table:"audit_logs"},bump).on("postgres_changes",{event:"*",schema:"public",table:"complaints"},bump);channel.subscribe();cleanup=()=>{void supabase.removeChannel(channel)}});return()=>{if(timer)window.clearTimeout(timer);cleanup()}},[role]);return <WorkspaceShell role={role}><Portal key={`${role}-${version}`} role={role}/></WorkspaceShell>}
function CustomerWorkspace(){const [version,setVersion]=useState(0),[ready,setReady]=useState(false),[hasCatalog,setHasCatalog]=useState(false),[problem,setProblem]=useState<string|null>(null);useEffect(()=>{let alive=true;async function init(){const check=await supabase.from("stores").select("id",{head:false}).limit(1);if(!alive)return;if(check.error){setProblem("تعذر تحميل المتاجر من قاعدة البيانات. جرّب تحديث التطبيق.");setReady(true);return}setHasCatalog((check.data||[]).length>0);setReady(true)}void init();return()=>{alive=false}},[]);useEffect(()=>{let cleanup=()=>{};void supabase.auth.getUser().then(({data})=>{const uid=data.user?.id;if(!uid)return;const channel=supabase.channel(`customer-workspace-${uid}`).on("postgres_changes",{event:"*",schema:"public",table:"orders",filter:`customer_id=eq.${uid}`},()=>setVersion(v=>v+1)).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter:`user_id=eq.${uid}`},()=>setVersion(v=>v+1)).on("postgres_changes",{event:"*",schema:"public",table:"stores"},()=>setVersion(v=>v+1)).subscribe();cleanup=()=>{void supabase.removeChannel(channel)}});return()=>cleanup()},[]);if(!ready)return <div className="boot" dir="rtl"><Logo size={64}/><div>جاري تحميل واجهة العميل…</div></div>;if(problem)return <WorkspaceShell role="customer"><div className="boot" dir="rtl"><Logo size={64}/><h2>{problem}</h2><button onClick={()=>location.reload()} style={{padding:"12px 18px",border:0,borderRadius:12,cursor:"pointer"}}>إعادة المحاولة</button></div></WorkspaceShell>;if(!hasCatalog)return <WorkspaceShell role="customer"><div className="boot" dir="rtl"><Logo size={64}/><h2>الخدمة متوقفة مؤقتًا</h2><p>مفيش متاجر متاحة حاليًا. هنرجع نعرض الخدمة أول ما المتاجر تكون جاهزة.</p><button onClick={()=>location.reload()} style={{padding:"12px 18px",border:0,borderRadius:12,cursor:"pointer"}}>تحديث</button></div></WorkspaceShell>;return <WorkspaceShell role="customer"><App key={version}/></WorkspaceShell>}
function Root(){const [roles,setRoles]=useState<Role[]>([]),[session,setSession]=useState<any>(null),[checked,setChecked]=useState(false);useEffect(()=>{let alive=true;(async()=>{const {data}=await supabase.auth.getSession();if(!alive)return;setSession(data.session);if(data.session){const {data:r}=await supabase.from("user_roles").select("role").eq("user_id",data.session.user.id);const next=((r||[]).map((x:any)=>x.role).filter((x:any)=>Object.prototype.hasOwnProperty.call(roleLabel,x)) as Role[]);setRoles(next)}setChecked(true)})();const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>{alive=false;data.subscription.unsubscribe()};},[]);useEffect(()=>{if("serviceWorker" in navigator)void navigator.serviceWorker.register("/sw.js")},[]);if(!checked)return <div className="boot"><Logo size={64}/><div style={{marginTop:8}}>جاري تشغيل طلبك…</div></div>;const params=new URLSearchParams(location.search);if(!session){if(params.get("signup")==="1"||params.get("login")==="1")return <AuthOnboarding/>;if(params.get("customer")==="1")return <CustomerWorkspace/>;return <AuthOnboarding/>}if(params.get("support")==="1"){const supportRole:Role=roles.includes("admin")?"admin":"customer";return <WorkspaceShell role={supportRole}><SupportCenter admin={roles.includes("admin")}/></WorkspaceShell>};const requested=params.get("role") as Role|null;let remembered:Role|null=null;try{remembered=localStorage.getItem("talabak_active_role") as Role|null}catch{};const validRemembered=remembered&&roles.includes(remembered)?remembered:null;if(requested==="customer"&&roles.includes("customer"))return <CustomerWorkspace/>;const staffRoles=roles.filter(r=>r!=="customer") as Exclude<Role,"customer">[];if(requested&&requested!=="customer"&&staffRoles.includes(requested as Exclude<Role,"customer">))return <LivePortal role={requested as Exclude<Role,"customer">}/>;if(validRemembered==="customer")return <CustomerWorkspace/>;if(validRemembered){const rememberedStaff=validRemembered as Exclude<Role,"customer">;if(staffRoles.includes(rememberedStaff))return <LivePortal role={rememberedStaff}/>;}if(roles.includes("customer"))return <CustomerWorkspace/>;if(roles.includes("admin"))return <LivePortal role="admin"/>;if(staffRoles.length===1)return <LivePortal role={staffRoles[0]}/>;if(staffRoles.length>1)return <RoleChooser roles={staffRoles} onPick={r=>{location.href=`/?role=${r}`}}/>;return <App/>}
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><AppErrorBoundary><Root/></AppErrorBoundary></React.StrictMode>);