import {useEffect,useMemo,useState} from "react";
import {supabase} from "./lib/supabase";

type Row={id:string;store_id:string;name:string;unit:string;quantity:number;low_stock_threshold:number;cost_price:number;updated_at:string};

export default function MerchantInventory(){
 const [rows,setRows]=useState<Row[]>([]),[stores,setStores]=useState<any[]>([]),[storeId,setStoreId]=useState(""),[name,setName]=useState(""),[unit,setUnit]=useState("قطعة"),[threshold,setThreshold]=useState("0"),[cost,setCost]=useState("0"),[busy,setBusy]=useState(false),[toast,setToast]=useState<string|null>(null),[delta,setDelta]=useState<Record<string,string>>({});
 const store=stores.find(s=>s.id===storeId);
 const low=useMemo(()=>rows.filter(r=>Number(r.quantity)<=Number(r.low_stock_threshold)),[rows]);
 useEffect(()=>{void load()},[]);
 async function load(){setBusy(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const s=await supabase.from("stores").select("id,name").eq("owner_id",user.id).order("created_at");const ss=s.data||[];setStores(ss);const sid=storeId||ss[0]?.id||"";if(sid){setStoreId(sid);const {data,error}=await supabase.from("inventory_items").select("*").eq("store_id",sid).order("name");if(error)return setToast(error.message);setRows(data||[])}else setRows([])}finally{setBusy(false)}}
 async function add(){if(!storeId||!name.trim())return setToast("اختار متجر واكتب اسم الصنف");const {data,error}=await supabase.from("inventory_items").insert({store_id:storeId,name:name.trim(),unit:unit.trim()||"قطعة",quantity:0,low_stock_threshold:Number(threshold||0),cost_price:Number(cost||0)}).select().single();if(error)return setToast(error.message);setRows(xs=>[...xs,data]);setName("");setThreshold("0");setCost("0");setToast("الصنف اتضاف للمخزون ✓")}
 async function adjust(row:Row){const amount=Number(delta[row.id]||0);if(!Number.isFinite(amount)||amount===0)return setToast("اكتب كمية زيادة أو نقص");const {data,error}=await supabase.rpc("merchant_adjust_inventory",{p_item_id:row.id,p_delta:amount,p_reason:amount>0?"إضافة مخزون":"صرف مخزون"});if(error)return setToast(error.message);setRows(xs=>xs.map(x=>x.id===row.id?data:x));setDelta(xs=>({...xs,[row.id]:""}));setToast(amount>0?"المخزون زاد ✓":"المخزون اتخفض ✓")}
 async function changeStore(id:string){setStoreId(id);const {data,error}=await supabase.from("inventory_items").select("*").eq("store_id",id).order("name");if(error)return setToast(error.message);setRows(data||[])}
 return <section className="merchant-inventory" dir="rtl"><div className="psection"><div><span className="pkicker">تشغيل المتجر</span><h2>المخزون</h2></div><div className="inventory-badges"><span>{rows.length} صنف</span>{low.length>0&&<strong>⚠ {low.length} منخفض</strong>}</div></div>{stores.length>0&&<select value={storeId} onChange={e=>void changeStore(e.target.value)}><option value="">اختار متجر</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}<div className="inventory-add"><input value={name} onChange={e=>setName(e.target.value)} placeholder="اسم الصنف / الخامة"/><input value={unit} onChange={e=>setUnit(e.target.value)} placeholder="الوحدة"/><input type="number" min="0" value={threshold} onChange={e=>setThreshold(e.target.value)} placeholder="حد التنبيه"/><input type="number" min="0" value={cost} onChange={e=>setCost(e.target.value)} placeholder="تكلفة الوحدة"/><button className="primary" disabled={busy||!store} onClick={()=>void add()}>+ إضافة</button></div><div className="inventory-list">{rows.map(r=><article className={`inventory-card ${Number(r.quantity)<=Number(r.low_stock_threshold)?"low":""}`} key={r.id}><div><b>{r.name}</b><small>{r.unit} • تكلفة {Math.round(Number(r.cost_price))} ج.م</small></div><strong>{Number(r.quantity).toLocaleString("ar-EG")} <span>{r.unit}</span></strong><div className="inventory-actions"><input type="number" step="1" value={delta[r.id]||""} onChange={e=>setDelta(x=>({...x,[r.id]:e.target.value}))} placeholder="+ / −"/><button onClick={()=>void adjust(r)}>تطبيق</button></div></article>)}{!rows.length&&<div className="pempty">{busy?"جاري التحميل…":"مفيش أصناف مخزون لسه."}</div>}</div>{toast&&<div className="toast">{toast}</div>}</section>;
}
