import { useEffect,useMemo,useState } from "react";
import { supabase } from "./lib/supabase";
import "./portal.css";

type Role="merchant"|"driver"|"admin";
type Order={id:string;store_id:string;customer_id:string;driver_id:string|null;status:string;subtotal:number;delivery_fee:number;total:number;delivery_address:string;created_at:string;updated_at:string;estimated_minutes:number|null;stores?:{name:string}|null};
type AppRow={id:string;applicant_id:string;business_name?:string;full_name?:string;phone:string;category?:string;vehicle_type?:string;address?:string;status:string;created_at:string};
const LABEL:Record<string,string>={pending:"جديد",accepted:"مقبول",preparing:"تجهيز",ready:"جاهز للسائق",assigned:"مع السائق",picked_up:"استلم",on_the_way:"في الطريق",delivered:"تم التسليم",cancelled:"ملغي",rejected:"مرفوض"};
const M_NEXT:Record<string,string>={pending:"accepted",accepted:"preparing",preparing:"ready"};
const D_NEXT:Record<string,string>={assigned:"picked_up",picked_up:"on_the_way",on_the_way:"delivered"};
const money=(n:number)=>`${new Intl.NumberFormat("ar-EG").format(Math.round(Number(n)||0))} ج.م`;

export default function Portal({role}:{role:Role}){
 const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<any>(null),[orders,setOrders]=useState<Order[]>([]),[stores,setStores]=useState<any[]>([]),[menus,setMenus]=useState<any[]>([]),[merchantApps,setMerchantApps]=useState<AppRow[]>([]),[driverApps,setDriverApps]=useState<AppRow[]>([]),[online,setOnline]=useState(false),[coords,setCoords]=useState({lat:null as number|null,lon:null as number|null}),[tab,setTab]=useState(role==="admin"?"overview":"orders"),[loading,setLoading]=useState(true),[toast,setToast]=useState<string|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)void load(data.session.user.id)})},[role]);
 useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(null),2300);return()=>window.clearTimeout(t)},[toast]);
 useEffect(()=>{if(role!=="driver"||!session)return;let watch:number|undefined;if(online&&navigator.geolocation){watch=navigator.geolocation.watchPosition(async p=>{const next={lat:p.coords.latitude,lon:p.coords.longitude};setCoords(next);await supabase.from("driver_status").upsert({user_id:session.user.id,is_online:true,latitude:next.lat,longitude:next.lon,updated_at:new Date().toISOString()})},()=>setToast("اسمح بالموقع عشان التوصيل الذكي يقدر يلاقيك"),{enableHighAccuracy:true,maximumAge:10000,timeout:15000})}return()=>{if(watch!==undefined)navigator.geolocation.clearWatch(watch)}},[online,role,session]);
 async function load(uid:string){setLoading(true);const p=await supabase.from("profiles").select("*").eq("id",uid).maybeSingle();if(p.data)setProfile(p.data);
  if(role==="merchant"){const s=await supabase.from("stores").select("*").eq("owner_id",uid).order("created_at");const ids=(s.data||[]).map((x:any)=>x.id);setStores(s.data||[]);if(ids.length){const [o,m]=await Promise.all([supabase.from("orders").select("*,stores(name)").in("store_id",ids).order("created_at",{ascending:false}).limit(100),supabase.from("menu_items").select("*").in("store_id",ids).order("category")]);setOrders(o.data||[]);setMenus(m.data||[])}}
  else if(role==="driver"){const st=await supabase.from("driver_status").select("*").eq("user_id",uid).maybeSingle();setOnline(Boolean(st.data?.is_online));setCoords({lat:st.data?.latitude??null,lon:st.data?.longitude??null});const {data}=await supabase.from("orders").select("*,stores(name)").or(`status.eq.ready,driver_id.eq.${uid}`).order("created_at",{ascending:false}).limit(100);setOrders(data||[])}
  else {const [o,s,d,ma,da]=await Promise.all([supabase.from("orders").select("*,stores(name)").order("created_at",{ascending:false}).limit(100),supabase.from("stores").select("id,name,category,is_open,rating").order("name"),supabase.from("driver_status").select("user_id,is_online"),supabase.from("merchant_applications").select("*").order("created_at",{ascending:false}).limit(50),supabase.from("driver_applications").select("*").order("created_at",{ascending:false}).limit(50)]);setOrders(o.data||[]);setStores(s.data||[]);setMenus([{count:(d.data||[]).filter((x:any)=>x.is_online).length}]);setMerchantApps(ma.data||[]);setDriverApps(da.data||[])}
  setLoading(false);
 }
 async function merchantMove(o:Order){const next=M_NEXT[o.status];if(!next)return;const {data,error}=await supabase.rpc("merchant_update_order",{p_order_id:o.id,p_status:next,p_estimated_minutes:o.estimated_minutes||30});if(error)return setToast(error.message);let moved:any=data;if(next==="ready"){const {data:driver}=await supabase.rpc("auto_assign_nearest_driver",{p_order_id:o.id});if(driver){moved={...moved,driver_id:driver,status:"assigned"};setToast("الطلب اتجه لسائق متاح ⚡")}else setToast("الطلب جاهز وبيستنى أول سائق متاح")}else setToast(`تم: ${LABEL[next]}`);setOrders(xs=>xs.map(x=>x.id===o.id?moved:{...x}))}
 async function acceptDriver(o:Order){if(!online)return setToast("حوّل حالتك أونلاين الأول");const {data,error}=await supabase.rpc("driver_accept_order",{p_order_id:o.id});if(error)return setToast(error.message);setOrders(xs=>xs.map(x=>x.id===o.id?data:x));setToast("الطلب بقى معاك ✓")}
 async function driverMove(o:Order){const next=D_NEXT[o.status];if(!next)return;const {data,error}=await supabase.rpc("driver_update_order",{p_order_id:o.id,p_status:next});if(error)return setToast(error.message);setOrders(xs=>xs.map(x=>x.id===o.id?data:x));setToast(`تم: ${LABEL[next]}`)}
 async function toggleOnline(){if(!session)return;const next=!online;if(next&&!navigator.geolocation)return setToast("المتصفح مش داعم للموقع");const payload:any={user_id:session.user.id,is_online:next,updated_at:new Date().toISOString()};if(!next){payload.latitude=null;payload.longitude=null}const {error}=await supabase.from("driver_status").upsert(payload);if(error)return setToast(error.message);setOnline(next);setToast(next?"أنت أونلاين ومستني طلبات ⚡":"تم إيقاف استقبال الطلبات")}
 async function adminDecision(kind:"merchant"|"driver",row:AppRow,status:"approved"|"rejected"){const rpc=kind==="merchant"?"admin_set_merchant_application":"admin_set_driver_application";const {error}=await supabase.rpc(rpc,{p_id:row.id,p_status:status});if(error)return setToast(error.message);if(kind==="merchant")setMerchantApps(xs=>xs.map(x=>x.id===row.id?{...x,status}:x));else setDriverApps(xs=>xs.map(x=>x.id===row.id?{...x,status}:x));setToast(status==="approved"?"تم الاعتماد ✓":"تم الرفض")}
 const revenue=orders.filter(o=>o.status==="delivered").reduce((a,o)=>a+Number(o.total),0),active=orders.filter(o=>!["delivered","cancelled","rejected"].includes(o.status)),available=orders.filter(o=>o.status==="ready"&&!o.driver_id),driverDone=orders.filter(o=>o.driver_id===session?.user?.id&&o.status==="delivered").length;
 const tabs=role==="admin"?[["overview","نظرة عامة"],["orders","الطلبات"],["stores","المتاجر"],["applications","طلبات الانضمام"]]:role==="merchant"?[["orders","الطلبات"],["menu","المنيو"],["stores","المتاجر"]]:[["orders","طلباتي"],["available","المتاح"],["earnings","الأرباح"]];
 if(loading)return <div className="portal-loading">جاري تجهيز مركزك…</div>;
 return <div className="portal" dir="rtl"><header className="phead"><div><span className="pkicker">طلبك • {role}</span><h1>{role==="merchant"?"مركز التاجر":role==="driver"?"مركز السائق":"لوحة الإدارة"}</h1><p>{profile?.full_name||session?.user?.email||"حساب موثوق"}</p></div><div className="phead-actions">{role==="driver"&&<button className={`online ${online?"on":""}`} onClick={()=>void toggleOnline()}><i/>{online?"أونلاين":"أوفلاين"}</button>}<button onClick={()=>{void supabase.auth.signOut();location.href="/"}}>خروج</button><a href="/?customer=1">واجهة العميل</a></div></header>
 <div className="pstats">{role==="admin"?<><Stat n={orders.length} t="كل الطلبات"/><Stat n={stores.length} t="المتاجر"/><Stat n={menus[0]?.count||0} t="سائقين أونلاين"/><Stat n={money(revenue)} t="مبيعات مسجلة"/></>:role==="merchant"?<><Stat n={orders.filter(o=>o.status==="pending").length} t="طلبات جديدة"/><Stat n={active.length} t="قيد التشغيل"/><Stat n={money(revenue)} t="مبيعات مكتملة"/><Stat n={stores.length} t="فروعك"/></>:<><Stat n={available.length} t="طلبات متاحة"/><Stat n={orders.filter(o=>o.driver_id===session?.user?.id&&o.status!=="delivered").length} t="معاك الآن"/><Stat n={driverDone} t="تم توصيلها"/><Stat n={online?"نشط":"متوقف"} t="الحالة"/></>}</div>
 <nav className="ptabs">{tabs.map(([k,t])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{t}</button>)}</nav><main className="pcontent">
 {(tab==="orders"||tab==="available")&&<section><div className="psection"><div><span className="pkicker">تشغيل لحظي</span><h2>{tab==="available"?"طلبات جاهزة للاستلام":"الطلبات"}</h2></div><button className="refresh" onClick={()=>session&&void load(session.user.id)}>تحديث ↻</button></div><div className="orderlist">{(tab==="available"?available:orders).map(o=><article className={tab==="available"?"offer":"porder"} key={o.id}><div><small>#{o.id.slice(0,7).toUpperCase()} • {new Date(o.created_at).toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit"})}</small><h3>{o.stores?.name||stores.find(s=>s.id===o.store_id)?.name||"متجر"}</h3><p>{o.delivery_address}</p></div><div className="porder-right"><span className={`badge ${o.status}`}>{LABEL[o.status]||o.status}</span><b>{money(Number(o.total))}</b>{role==="merchant"&&M_NEXT[o.status]&&<button onClick={()=>void merchantMove(o)}>{o.status==="pending"?"قبول الطلب":"تحديث الحالة"}</button>}{role==="driver"&&o.status==="ready"&&!o.driver_id&&<button onClick={()=>void acceptDriver(o)}>استلام الطلب</button>}{role==="driver"&&o.driver_id===session?.user?.id&&D_NEXT[o.status]&&<button onClick={()=>void driverMove(o)}>{D_NEXT[o.status]==="delivered"?"تم التسليم":"تحديث"}</button>}</div></article>)}</div>{role==="driver"&&online&&coords.lat&&coords.lon&&<div className="location-strip">📍 موقعك متصل • {coords.lat.toFixed(4)}, {coords.lon.toFixed(4)} • التوزيع الذكي يقدر يستخدم موقعك</div>}{!(tab==="available"?available:orders).length&&<div className="pempty">مفيش طلبات هنا حاليًا.</div>}</section>}
 {tab==="menu"&&role==="merchant"&&<section><div className="psection"><div><span className="pkicker">كتالوجك</span><h2>المنيو والأصناف</h2></div></div><div className="menu-table">{menus.map(m=><div key={m.id}><div><b>{m.name}</b><small>{m.category||"بدون تصنيف"} • {m.is_available?"متاح":"متوقف"}</small></div><strong>{money(Number(m.price))}</strong></div>)}</div>{!menus.length&&<div className="pempty">مفيش أصناف مضافة.</div>}</section>}
 {tab==="stores"&&<section><div className="psection"><div><span className="pkicker">الفروع</span><h2>{role==="admin"?"كل المتاجر":"متاجرك"}</h2></div></div><div className="store-list">{stores.map(s=><div className="pstore" key={s.id}><div><b>{s.name}</b><small>{s.category} • ★ {Number(s.rating||0).toFixed(1)}</small></div><span className={s.is_open?"open":"closed"}>{s.is_open?"مفتوح":"مغلق"}</span></div>)}</div></section>}
 {tab==="applications"&&role==="admin"&&<section><div className="psection"><div><span className="pkicker">مراجعة واعتماد</span><h2>طلبات الانضمام</h2></div><button className="refresh" onClick={()=>session&&void load(session.user.id)}>تحديث ↻</button></div><h3 className="subhead">التجار</h3><div className="app-list">{merchantApps.map(a=><Application key={a.id} row={a} type="merchant" decide={adminDecision}/>)}</div><h3 className="subhead">السائقون</h3><div className="app-list">{driverApps.map(a=><Application key={a.id} row={a} type="driver" decide={adminDecision}/>)}</div>{!merchantApps.length&&!driverApps.length&&<div className="pempty">مفيش طلبات انضمام.</div>}</section>}
 {tab==="overview"&&role==="admin"&&<section><div className="admin-grid"><div className="big-card"><span className="pkicker">تشغيل</span><strong>{active.length}</strong><p>طلبات نشطة الآن.</p></div><div className="big-card"><span className="pkicker">آخر الطلبات</span>{orders.slice(0,7).map(o=><div className="mini-row" key={o.id}><span>#{o.id.slice(0,5)}</span><b>{LABEL[o.status]}</b><strong>{money(Number(o.total))}</strong></div>)}</div></div></section>}
 {tab==="earnings"&&role==="driver"&&<section><div className="big-earning"><span className="pkicker">أرباح الطلبات المسلمة</span><strong>{money(orders.filter(o=>o.driver_id===session?.user?.id&&o.status==="delivered").reduce((a,o)=>a+Number(o.total)*.15,0))}</strong><p>الحساب الأولي هنا 15% من قيمة الطلبات المسلّمة.</p></div></section>}
 </main>{toast&&<div className="ptoast">{toast}</div>}</div>;
}
function Application({row,type,decide}:{row:AppRow;type:"merchant"|"driver";decide:(t:"merchant"|"driver",r:AppRow,s:"approved"|"rejected")=>Promise<void>}){return <article className="app-row"><div><small>#{row.id.slice(0,7).toUpperCase()} • {new Date(row.created_at).toLocaleDateString("ar-EG")}</small><h3>{type==="merchant"?row.business_name:row.full_name}</h3><p>{row.phone} {type==="merchant"?`• ${row.category||""} • ${row.address||""}`:`• ${row.vehicle_type||"مركبة"}`}</p></div><div className="app-actions"><span className={`badge ${row.status}`}>{row.status==="approved"?"معتمد":row.status==="rejected"?"مرفوض":"قيد المراجعة"}</span>{row.status==="pending"&&<><button onClick={()=>void decide(type,row,"approved")}>اعتماد</button><button className="reject" onClick={()=>void decide(type,row,"rejected")}>رفض</button></>}</div></article>}
function Stat({n,t}:{n:any;t:string}){return <div className="stat"><b>{n}</b><span>{t}</span></div>}
