import { useEffect,useMemo,useState } from "react";
import { supabase } from "./lib/supabase";
import "./portal.css";

type Role="merchant"|"driver"|"admin";
type Order={id:string;store_id:string;customer_id:string;driver_id:string|null;status:string;subtotal:number;delivery_fee:number;total:number;delivery_address:string;created_at:string;estimated_minutes:number|null;stores?:{name:string}|null};
const labels:Record<string,string>={pending:"جديد",accepted:"مقبول",preparing:"جاري التجهيز",ready:"جاهز للسائق",assigned:"مع السائق",picked_up:"تم الاستلام",on_the_way:"في الطريق",delivered:"تم التسليم",cancelled:"ملغي",rejected:"مرفوض"};
const nextMerchant:Record<string,string>={pending:"accepted",accepted:"preparing",preparing:"ready"};
const nextDriver:Record<string,string>={assigned:"picked_up",picked_up:"on_the_way",on_the_way:"delivered"};
const money=(n:number)=>`${new Intl.NumberFormat("ar-EG").format(Math.round(n))} ج.م`;
export default function Portal({role}:{role:Role}){
 const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<any>(null),[stores,setStores]=useState<any[]>([]),[orders,setOrders]=useState<Order[]>([]),[menus,setMenus]=useState<any[]>([]),[online,setOnline]=useState(false),[loading,setLoading]=useState(true),[toast,setToast]=useState<string|null>(null),[tab,setTab]=useState(role==="admin"?"overview":"orders"),[selectedStore,setSelectedStore]=useState<string|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load(data.session.user.id)});},[role]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(null),2500);return()=>clearTimeout(t)}},[toast]);
 async function load(uid:string){setLoading(true);const p=await supabase.from("profiles").select("*").eq("id",uid).maybeSingle();if(p.data)setProfile(p.data);
  if(role==="merchant"){const s=await supabase.from("stores").select("*").eq("owner_id",uid).order("created_at");setStores(s.data||[]);const ids=(s.data||[]).map((x:any)=>x.id);if(ids.length){const o=await supabase.from("orders").select("*,stores(name)").in("store_id",ids).order("created_at",{ascending:false}).limit(60);setOrders(o.data||[]);const m=await supabase.from("menu_items").select("*").in("store_id",ids).order("category");setMenus(m.data||[])}}
  if(role==="driver"){const st=await supabase.from("driver_status").select("*").eq("user_id",uid).maybeSingle();setOnline(!!st.data?.is_online);const o=await supabase.from("orders").select("*,stores(name)").or(`status.eq.ready,driver_id.eq.${uid}`).order("created_at",{ascending:false}).limit(60);setOrders(o.data||[])}
  if(role==="admin"){const [o,s,m,d,ma,da]=await Promise.all([supabase.from("orders").select("*,stores(name)").order("created_at",{ascending:false}).limit(100),supabase.from("stores").select("id,name,category,is_open,rating"),supabase.from("menu_items").select("id"),supabase.from("driver_status").select("user_id,is_online"),supabase.from("merchant_applications").select("*").order("created_at",{ascending:false}).limit(20),supabase.from("driver_applications").select("*").order("created_at",{ascending:false}).limit(20)]);setOrders(o.data||[]);setStores(s.data||[]);setMenus([{count:m.data?.length||0},{drivers:d.data?.filter((x:any)=>x.is_online).length||0},{merchantApps:ma.data||[]},{driverApps:da.data||[]}])}
  setLoading(false)
 }
 async function merchantMove(o:Order){const ns=nextMerchant[o.status];if(!ns)return;const {error}=await supabase.rpc("merchant_update_order",{p_order_id:o.id,p_status:ns,p_estimated_minutes:o.estimated_minutes||30});if(error){setToast(error.message);return}setOrders(x=>x.map(v=>v.id===o.id?{...v,status:ns}:v));setToast(`تم نقل الطلب إلى ${labels[ns]}`)}
 async function driverAccept(o:Order){const {data,error}=await supabase.rpc("driver_accept_order",{p_order_id:o.id});if(error){setToast(error.message);return}setOrders(x=>x.map(v=>v.id===o.id?data:v));setToast("الطلب اتربط بيك ✓")}
 async function driverMove(o:Order){const ns=nextDriver[o.status];if(!ns)return;const {data,error}=await supabase.rpc("driver_update_order",{p_order_id:o.id,p_status:ns});if(error){setToast(error.message);return}setOrders(x=>x.map(v=>v.id===o.id?data:v));setToast(`تم تحديث الحالة إلى ${labels[ns]}`)}
 async function toggleOnline(){if(!session)return;const {error}=await supabase.from("driver_status").upsert({user_id:session.user.id,is_online:!online,updated_at:new Date().toISOString()});if(error){setToast(error.message);return}setOnline(!online);setToast(!online?"أنت أونلاين — جاهز للطلبات ⚡":"تم إيقاف استقبال الطلبات")}
 const revenue=orders.filter(o=>o.status==="delivered").reduce((a,o)=>a+Number(o.total),0);const active=orders.filter(o=>!["delivered","cancelled","rejected"].includes(o.status));const ready=orders.filter(o=>o.status==="ready"&&role==="driver"&&o.driver_id===null);
 const header=role==="merchant"?"مركز التاجر":role==="driver"?"مركز السائق":"لوحة الإدارة";
 if(loading)return <div className="portal-loading">جاري تجهيز مركزك…</div>;
 return <div className="portal" dir="rtl"><header className="phead"><div><span className="pkicker">طلبك • {role}</span><h1>{header}</h1><p>{profile?.full_name||session?.user?.email||"حساب موثوق"}</p></div><div className="phead-actions">{role==="driver"&&<button className={`online ${online?"on":""}`} onClick={toggleOnline}><i/> {online?"أونلاين":"أوفلاين"}</button>}<button onClick={()=>{supabase.auth.signOut();location.reload()}}>خروج</button><a href="/?customer=1">واجهة العميل</a></div></header>
 <div className="pstats">{role==="admin"?<><Stat n={orders.length} t="كل الطلبات"/><Stat n={stores.length} t="المتاجر"/><Stat n={(menus[1]?.drivers||0) as number} t="سائقين أونلاين"/><Stat n={money(revenue)} t="مبيعات مسجلة"/></>:role==="merchant"?<><Stat n={orders.filter(o=>o.status==="pending").length} t="طلبات جديدة"/><Stat n={active.length} t="قيد التشغيل"/><Stat n={money(revenue)} t="مبيعات مكتملة"/><Stat n={stores.length} t="فروعك"/></>:<><Stat n={ready.length} t="طلبات متاحة"/><Stat n={orders.filter(o=>o.driver_id===session?.user?.id&&o.status!=="delivered").length} t="معاك الآن"/><Stat n={orders.filter(o=>o.status==="delivered"&&o.driver_id===session?.user?.id).length} t="تم توصيلها"/><Stat n={online?"نشط":"متوقف"} t="حالتك"/></>}</div>
 <nav className="ptabs">{(role==="admin"?["overview","orders","stores","applications"]:role==="merchant"?["orders","menu","stores"]:["orders","available","earnings"]).map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t==="overview"?"نظرة عامة":t==="orders"?"الطلبات":t==="available"?"المتاح الآن":t==="earnings"?"الأرباح":t==="menu"?"المنيو":t==="stores"?"المتاجر":"طلبات الانضمام"}</button>)}</nav>
 <main className="pcontent">{tab==="orders"&&<section><div className="psection"><div><span className="pkicker">تشغيل لحظي</span><h2>الطلبات</h2></div><button className="refresh" onClick={()=>session&&load(session.user.id)}>تحديث ↻</button></div><div className="orderlist">{orders.map(o=><article className="porder" key={o.id}><div><small>#{o.id.slice(0,7).toUpperCase()} • {new Date(o.created_at).toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit"})}</small><h3>{o.stores?.name||stores.find(s=>s.id===o.store_id)?.name||"متجر"}</h3><p>{o.delivery_address}</p></div><div className="porder-right"><span className={`badge ${o.status}`}>{labels[o.status]||o.status}</span><b>{money(Number(o.total))}</b>{role==="merchant"&&nextMerchant[o.status]&&<button onClick={()=>merchantMove(o)}>{o.status==="pending"?"قبول الطلب":"تحديث الحالة"}</button>}{role==="driver"&&o.status==="ready"&&o.driver_id===null&&<button onClick={()=>driverAccept(o)}>استلام الطلب</button>}{role==="driver"&&o.driver_id===session?.user?.id&&nextDriver[o.status]&&<button onClick={()=>driverMove(o)}>{nextDriver[o.status]==="delivered"?"تم التسليم":"تم ✓"}</button>}</div></article>)}</div>{!orders.length&&<div className="pempty">مفيش طلبات في الحالة دي.</div>}</section>}
 {tab==="available"&&role==="driver"&&<section><div className="psection"><div><span className="pkicker">اختيار شغل</span><h2>طلبات قريبة ومتاحة</h2></div></div><div className="orderlist">{ready.map(o=><article className="offer" key={o.id}><div><span>⚡ جاهز للاستلام</span><h3>{o.stores?.name||"متجر"}</h3><p>{o.delivery_address}</p></div><div><b>{money(Number(o.total))}</b><button onClick={()=>driverAccept(o)}>استلم</button></div></article>)}</div></section>}
 {tab==="earnings"&&role==="driver"&&<section><div className="big-earning"><span className="pkicker">أرباحك المسجلة</span><strong>{money(orders.filter(o=>o.driver_id===session?.user?.id&&o.status==="delivered").reduce((a,o)=>a+Number(o.total)*.15,0))}</strong><p>نسبة التشغيل المعروضة مبدئيًا 15% من قيمة الطلبات المسلّمة.</p></div></section>}
 {tab==="menu"&&role==="merchant"&&<section><div className="psection"><div><span className="pkicker">كتالوجك</span><h2>المنيو والأصناف</h2></div></div><div className="menu-table">{menus.map(m=><div key={m.id}><div><b>{m.name}</b><small>{m.category} • {m.is_available?"متاح":"متوقف"}</small></div><strong>{money(Number(m.price))}</strong></div>)}</div></section>}
 {tab==="stores"&&<section><div className="psection"><div><span className="pkicker">إدارة الفروع</span><h2>{role==="admin"?"كل المتاجر":"متاجرك"}</h2></div></div><div className="store-list">{stores.map(s=><div className="pstore" key={s.id}><div><b>{s.name}</b><small>{s.category} • ★ {Number(s.rating||0).toFixed(1)}</small></div><span className={s.is_open?"open":"closed"}>{s.is_open?"مفتوح":"مغلق"}</span></div>)}</div></section>}
 {tab==="applications"&&role==="admin"&&<section><div className="psection"><div><span className="pkicker">العمليات</span><h2>طلبات الانضمام</h2></div></div><div className="pempty">طلبات التجار والسائقين تُدار من قاعدة البيانات مباشرة، مع حالة الطلب وصلاحيات الإدارة في النسخة الآمنة.</div></section>}
 {tab==="overview"&&role==="admin"&&<section><div className="admin-grid"><div className="big-card"><span className="pkicker">تشغيل اليوم</span><strong>{active.length}</strong><p>طلبات قيد التنفيذ حاليًا.</p></div><div className="big-card"><span className="pkicker">آخر الطلبات</span>{orders.slice(0,5).map(o=><div className="mini-row" key={o.id}><span>#{o.id.slice(0,5)}</span><b>{labels[o.status]}</b><strong>{money(Number(o.total))}</strong></div>)}</div></div></section>}</main>{toast&&<div className="ptoast">{toast}</div>}</div>}
}
function Stat({n,t}:{n:any;t:string}){return <div className="stat"><b>{n}</b><span>{t}</span></div>}
