import { useEffect,useMemo,useState } from "react";
import { supabase } from "./lib/supabase";
import "./portal.css";

type Role="merchant"|"driver"|"admin";
type Order={id:string;store_id:string;customer_id:string;driver_id:string|null;status:string;subtotal:number;delivery_fee:number;total:number;delivery_address:string;created_at:string;updated_at:string;estimated_minutes:number|null;stores?:{name:string}|null};
type AppRow={id:string;applicant_id:string;business_name?:string;full_name?:string;phone:string;category?:string;vehicle_type?:string;address?:string;status:string;created_at:string};
type Person={user_id:string;full_name:string;phone:string|null;is_active:boolean;roles:string;is_online:boolean;latitude:number|null;longitude:number|null};
const LABEL:Record<string,string>={pending:"جديد",accepted:"مقبول",preparing:"تجهيز",ready:"جاهز للسائق",assigned:"مع السائق",picked_up:"استلم",on_the_way:"في الطريق",delivered:"تم التسليم",cancelled:"ملغي",rejected:"مرفوض"};
const ORDER_STATUSES=Object.keys(LABEL);
const M_NEXT:Record<string,string>={pending:"accepted",accepted:"preparing",preparing:"ready"};
const D_NEXT:Record<string,string>={assigned:"picked_up",picked_up:"on_the_way",on_the_way:"delivered"};
const money=(n:number)=>`${new Intl.NumberFormat("ar-EG").format(Math.round(Number(n)||0))} ج.م`;
const msg=(e:any)=>e?.message||"حصلت مشكلة. جرّب تاني.";

export default function Portal({role}:{role:Role}){
 const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<any>(null),[orders,setOrders]=useState<Order[]>([]),[stores,setStores]=useState<any[]>([]),[menus,setMenus]=useState<any[]>([]),[merchantApps,setMerchantApps]=useState<AppRow[]>([]),[driverApps,setDriverApps]=useState<AppRow[]>([]),[users,setUsers]=useState<Person[]>([]),[driverUsers,setDriverUsers]=useState<Person[]>([]),[audit,setAudit]=useState<any[]>([]),[online,setOnline]=useState(false),[tab,setTab]=useState(role==="admin"?"overview":"orders"),[loading,setLoading]=useState(true),[toast,setToast]=useState<string|null>(null),[selectedStore,setSelectedStore]=useState<string>(""),[newItem,setNewItem]=useState({name:"",description:"",price:"",category:"أصناف"}),[notify,setNotify]=useState({title:"",body:"",userId:""}),[orderFilter,setOrderFilter]=useState("all"),[editingStore,setEditingStore]=useState<any|null>(null);
 const activeStore=useMemo(()=>stores.find(s=>s.id===selectedStore)||stores[0],[stores,selectedStore]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)void load(data.session.user.id)})},[role]);
 useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(null),2500);return()=>window.clearTimeout(t)},[toast]);
 useEffect(()=>{if(role!=="driver"||!session||!online||!navigator.geolocation)return;const watch=navigator.geolocation.watchPosition(async p=>{const {error}=await supabase.rpc("update_driver_location",{p_latitude:p.coords.latitude,p_longitude:p.coords.longitude,p_accuracy_meters:p.coords.accuracy});if(error)setToast(msg(error))},()=>setToast("اسمح للموقع علشان استقبال الطلبات والتوزيع الذكي يشتغل"),{enableHighAccuracy:true,maximumAge:10000,timeout:15000});return()=>navigator.geolocation.clearWatch(watch)},[role,session,online]);
 async function load(uid:string){setLoading(true);try{const p=await supabase.from("profiles").select("*").eq("id",uid).maybeSingle();if(p.data)setProfile(p.data);
  if(role==="merchant"){const s=await supabase.from("stores").select("*").eq("owner_id",uid).order("created_at");const list=s.data||[];setStores(list);if(!selectedStore&&list[0])setSelectedStore(list[0].id);const ids=list.map((x:any)=>x.id);if(ids.length){const [o,m]=await Promise.all([supabase.from("orders").select("*,stores(name)").in("store_id",ids).order("created_at",{ascending:false}).limit(150),supabase.from("menu_items").select("*").in("store_id",ids).order("category")]);setOrders(o.data||[]);setMenus(m.data||[])}else{setOrders([]);setMenus([])}}
  else if(role==="driver"){const st=await supabase.from("driver_status").select("*").eq("user_id",uid).maybeSingle();setOnline(Boolean(st.data?.is_online));const {data}=await supabase.from("orders").select("*,stores(name)").or(`status.eq.ready,driver_id.eq.${uid}`).order("created_at",{ascending:false}).limit(100);setOrders(data||[])}
  else {const [o,s,ma,da,u,a]=await Promise.all([supabase.from("orders").select("*,stores(name)").order("created_at",{ascending:false}).limit(250),supabase.from("stores").select("*").order("name"),supabase.from("merchant_applications").select("*").order("created_at",{ascending:false}).limit(100),supabase.from("driver_applications").select("*").order("created_at",{ascending:false}).limit(100),supabase.rpc("admin_list_users"),supabase.from("audit_logs").select("*").order("created_at",{ascending:false}).limit(120)]);setOrders(o.data||[]);setStores(s.data||[]);setMerchantApps(ma.data||[]);setDriverApps(da.data||[]);setUsers(u.data||[]);setDriverUsers((u.data||[]).filter((x:any)=>x.roles.split(",").includes("driver")));setAudit(a.data||[]);if(!selectedStore&&s.data?.[0])setSelectedStore(s.data[0].id)}
 }finally{setLoading(false)}}
 async function merchantMove(o:Order){const next=M_NEXT[o.status];if(!next)return;const {data,error}=await supabase.rpc("merchant_update_order",{p_order_id:o.id,p_status:next,p_estimated_minutes:o.estimated_minutes||30});if(error)return setToast(msg(error));setOrders(xs=>xs.map(x=>x.id===o.id?data:x));if(next==="ready"){const {data:driver,error:e}=await supabase.rpc("auto_assign_nearest_driver",{p_order_id:o.id});if(e)return setToast(msg(e));setToast(driver?"الطلب اتسند لسائق قريب ⚡":"الطلب جاهز ومستني سائق متاح")}else setToast(`تم تحديث الطلب: ${LABEL[next]}`)}
 async function acceptDriver(o:Order){if(!online)return setToast("حوّل حالتك أونلاين الأول");const {data,error}=await supabase.rpc("driver_accept_order",{p_order_id:o.id});if(error)return setToast(msg(error));setOrders(xs=>xs.map(x=>x.id===o.id?data:x));setToast("الطلب بقى معاك ✓")}
 async function driverMove(o:Order){const next=D_NEXT[o.status];if(!next)return;const {data,error}=await supabase.rpc("driver_update_order",{p_order_id:o.id,p_status:next});if(error)return setToast(msg(error));setOrders(xs=>xs.map(x=>x.id===o.id?data:x));setToast(`تم: ${LABEL[next]}`)}
 async function toggleOnline(){if(!session)return;const next=!online;if(next&&!navigator.geolocation)return setToast("المتصفح مش داعم للموقع");if(!next){const {error}=await supabase.from("driver_status").update({is_online:false,updated_at:new Date().toISOString()}).eq("user_id",session.user.id);if(error)return setToast(msg(error));setOnline(false);return setToast("تم إيقاف استقبال الطلبات")}
  navigator.geolocation.getCurrentPosition(async p=>{const {error}=await supabase.rpc("update_driver_location",{p_latitude:p.coords.latitude,p_longitude:p.coords.longitude,p_accuracy_meters:p.coords.accuracy});if(error)return setToast(msg(error));setOnline(true);setToast("أنت أونلاين ومستني طلبات ⚡")},()=>setToast("اسمح للموقع علشان نفعّل حالتك أونلاين"),{enableHighAccuracy:true,maximumAge:0,timeout:15000});}
 async function adminDecision(kind:"merchant"|"driver",row:AppRow,status:"approved"|"rejected"){const {error}=await supabase.rpc(kind==="merchant"?"admin_set_merchant_application":"admin_set_driver_application",{p_id:row.id,p_status:status});if(error)return setToast(msg(error));if(kind==="merchant")setMerchantApps(xs=>xs.map(x=>x.id===row.id?{...x,status}:x));else setDriverApps(xs=>xs.map(x=>x.id===row.id?{...x,status}:x));await load(session.user.id);setToast(status==="approved"?"تم الاعتماد ✓":"تم الرفض")}
 async function roleToggle(u:Person,r:"customer"|"merchant"|"driver"|"admin",enabled:boolean){const {error}=await supabase.rpc("admin_set_role",{p_user_id:u.user_id,p_role:r,p_enabled:enabled});if(error)return setToast(msg(error));await load(session.user.id)}
 async function activeToggle(u:Person){const {error}=await supabase.rpc("admin_set_user_active",{p_user_id:u.user_id,p_active:!u.is_active});if(error)return setToast(msg(error));await load(session.user.id)}
 async function adminOrder(o:Order,status:string,driverId:string|null){const {data,error}=await supabase.rpc("admin_set_order",{p_order_id:o.id,p_status:status,p_driver_id:driverId||null});if(error)return setToast(msg(error));setOrders(xs=>xs.map(x=>x.id===o.id?data:x));setToast("تم تعديل الطلب بواسطة الإدارة")}
 async function saveStore(s:any){const {data,error}=await supabase.rpc("admin_set_store",{p_store_id:s.id,p_name:s.name,p_category:s.category,p_address:s.address,p_delivery_fee:Number(s.delivery_fee),p_min_order:Number(s.min_order),p_prep_minutes:Number(s.prep_minutes),p_is_open:Boolean(s.is_open)});if(error)return setToast(msg(error));setStores(xs=>xs.map(x=>x.id===s.id?data:x));setEditingStore(null);setToast("بيانات المتجر اتحدثت ✓")}
 async function addMenu(){if(!newItem.name.trim()||!activeStore)return setToast("اختار متجر واكتب اسم الصنف");const {data,error}=await supabase.rpc("admin_add_menu_item",{p_store_id:activeStore.id,p_name:newItem.name,p_description:newItem.description,p_price:Number(newItem.price||0),p_category:newItem.category});if(error)return setToast(msg(error));setMenus(xs=>[...xs,data]);setNewItem({name:"",description:"",price:"",category:"أصناف"});setToast("الصنف اتضاف ✓")}
 async function editMenu(m:any){const {data,error}=await supabase.rpc("admin_set_menu_item",{p_item_id:m.id,p_name:m.name,p_description:m.description,p_price:Number(m.price),p_category:m.category,p_is_available:Boolean(m.is_available)});if(error)return setToast(msg(error));setMenus(xs=>xs.map(x=>x.id===m.id?data:x));setToast("الصنف اتحدث ✓")}
 async function editMerchantMenu(m:any){const {error}=await supabase.from("menu_items").update({name:m.name,description:m.description,price:Number(m.price),is_available:m.is_available,updated_at:new Date().toISOString()}).eq("id",m.id);if(error)return setToast(msg(error));setToast("تم حفظ الصنف ✓")}
 async function sendNotification(){if(!notify.title.trim()||!notify.body.trim())return setToast("اكتب عنوان ونص الإشعار");const {error}=await supabase.rpc("admin_send_notification",{p_user_id:notify.userId||null,p_title:notify.title,p_body:notify.body,p_kind:"admin"});if(error)return setToast(msg(error));setNotify({title:"",body:"",userId:""});setToast(notify.userId?"الإشعار اتبعت ✓":"الإشعار اتبعت للمستخدمين النشطين ✓")}
 const delivered=orders.filter(o=>o.status==="delivered"),activeOrders=orders.filter(o=>!["delivered","cancelled","rejected"].includes(o.status)),available=orders.filter(o=>o.status==="ready"&&!o.driver_id),revenue=delivered.reduce((a,o)=>a+Number(o.total),0),filteredOrders=orderFilter==="all"?orders:orders.filter(o=>o.status===orderFilter);
 const tabs=role==="admin"?[['overview','نظرة عامة'],['orders','الطلبات'],['users','المستخدمون'],['stores','المتاجر'],['menu','المنيو'],['applications','طلبات الانضمام'],['notifications','الإشعارات'],['audit','سجل الإدارة']]:role==="merchant"?[['orders','الطلبات'],['menu','المنيو'],['stores','المتجر']]:[['orders','طلباتي'],['available','المتاح'],['earnings','الأرباح']];
 if(loading)return <div className="portal-loading">جاري تجهيز مركزك…</div>;
 return <div className="portal" dir="rtl"><header className="phead"><div><span className="pkicker">طلبك • {role==="admin"?"إدارة":role==="merchant"?"تاجر":"سائق"}</span><h1>{role==="merchant"?"مركز التاجر":role==="driver"?"مركز السائق":"لوحة الإدارة"}</h1><p>{profile?.full_name||profile?.phone||"حساب موثوق"}</p></div><div className="phead-actions">{role==="driver"&&<button className={`online ${online?"on":""}`} onClick={()=>void toggleOnline()}><i/>{online?"أونلاين":"أوفلاين"}</button>}<button onClick={()=>{void supabase.auth.signOut();location.href="/"}}>خروج</button><a href="/?customer=1">واجهة العميل</a></div></header>
 <div className="pstats">{role==="admin"?<><Stat n={orders.length} t="كل الطلبات"/><Stat n={activeOrders.length} t="طلبات نشطة"/><Stat n={users.length} t="الحسابات"/><Stat n={money(revenue)} t="مبيعات مكتملة"/></>:role==="merchant"?<><Stat n={orders.filter(o=>o.status==="pending").length} t="طلبات جديدة"/><Stat n={activeOrders.length} t="قيد التشغيل"/><Stat n={money(revenue)} t="مبيعات مكتملة"/><Stat n={stores.length} t="فروعك"/></>:<><Stat n={available.length} t="طلبات متاحة"/><Stat n={orders.filter(o=>o.driver_id===session?.user?.id&&!['delivered','cancelled'].includes(o.status)).length} t="معاك الآن"/><Stat n={delivered.filter(o=>o.driver_id===session?.user?.id).length} t="تم توصيلها"/><Stat n={online?"نشط":"متوقف"} t="الحالة"/></>}</div>
 <nav className="ptabs">{tabs.map(([k,t])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{t}</button>)}</nav><main className="pcontent">
 {(tab==="orders"||tab==="available")&&<section><div className="psection"><div><span className="pkicker">تشغيل لحظي</span><h2>{tab==="available"?"طلبات جاهزة للاستلام":"الطلبات"}</h2></div><div className="psection-actions"><select value={orderFilter} onChange={e=>setOrderFilter(e.target.value)}><option value="all">كل الحالات</option>{ORDER_STATUSES.map(s=><option key={s} value={s}>{LABEL[s]}</option>)}</select><button className="refresh" onClick={()=>session&&void load(session.user.id)}>تحديث ↻</button></div></div><div className="orderlist">{(tab==="available"?available:filteredOrders).map(o=><article className={tab==="available"?"offer":"porder"} key={o.id}><div><small>#{o.id.slice(0,7).toUpperCase()} • {new Date(o.created_at).toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit"})}</small><h3>{o.stores?.name||stores.find(s=>s.id===o.store_id)?.name||"متجر"}</h3><p>{o.delivery_address}</p></div><div className="porder-right"><span className={`badge ${o.status}`}>{LABEL[o.status]||o.status}</span><b>{money(Number(o.total))}</b>{role==="merchant"&&M_NEXT[o.status]&&<button onClick={()=>void merchantMove(o)}>{o.status==="pending"?"قبول الطلب":"تحديث الحالة"}</button>}{role==="driver"&&o.status==="ready"&&!o.driver_id&&<button onClick={()=>void acceptDriver(o)}>استلام الطلب</button>}{role==="driver"&&o.driver_id===session?.user?.id&&D_NEXT[o.status]&&<button onClick={()=>void driverMove(o)}>{D_NEXT[o.status]==="delivered"?"تم التسليم":"تحديث"}</button>}{role==="admin"&&<div className="inline-admin"><select value={o.status} onChange={e=>void adminOrder(o,e.target.value,o.driver_id)}>{ORDER_STATUSES.map(s=><option key={s} value={s}>{LABEL[s]}</option>)}</select><select value={o.driver_id||""} onChange={e=>void adminOrder(o,o.status,e.target.value||null)}><option value="">بدون سائق</option>{driverUsers.map(d=><option key={d.user_id} value={d.user_id}>{d.full_name||d.phone||d.user_id.slice(0,6)}</option>)}</select></div>}</div></article>)}</div>{role==="driver"&&online&&<div className="location-strip">📍 التتبع مفعّل — خلّي التطبيق شغال أثناء الشغل علشان التوزيع يفضل دقيق.</div>}{!(tab==="available"?available:filteredOrders).length&&<div className="pempty">مفيش نتائج هنا حاليًا.</div>}</section>}
 {tab==="overview"&&role==="admin"&&<section><div className="admin-grid"><div className="big-card"><span className="pkicker">التشغيل الحالي</span><strong>{activeOrders.length}</strong><p>طلب نشط يحتاج متابعة.</p></div><div className="big-card"><span className="pkicker">سائقون أونلاين</span><strong>{users.filter(u=>u.is_online).length}</strong><p>سائقين متاحين للمراقبة.</p></div><div className="big-card"><span className="pkicker">طلبات جاهزة</span><strong>{available.length}</strong><p>محتاجة سائق.</p></div><div className="big-earning"><span>إجمالي المبيعات المكتملة</span><strong>{money(revenue)}</strong><p>إجمالي الطلبات المكتملة المحمّلة في اللوحة الحالية.</p></div></div></section>}
 {tab==="users"&&role==="admin"&&<section><div className="psection"><div><span className="pkicker">إدارة الحسابات</span><h2>كل المستخدمين والأدوار</h2></div><button className="refresh" onClick={()=>session&&void load(session.user.id)}>تحديث ↻</button></div><div className="user-list">{users.map(u=><article className="user-card" key={u.user_id}><div className="user-main"><b>{u.full_name||"بدون اسم"}</b><span>{u.phone||"رقم غير محفوظ"}</span><small>{u.is_online?"🟢 أونلاين":"⚪ أوفلاين"}{u.latitude!==null&&u.longitude!==null?` • ${u.latitude.toFixed(4)}, ${u.longitude.toFixed(4)}`:""}</small></div><div className="role-controls">{(["customer","merchant","driver","admin"] as const).map(r=><label key={r}><input type="checkbox" checked={u.roles.split(",").includes(r)} onChange={e=>void roleToggle(u,r,e.target.checked)}/>{r==="customer"?"عميل":r==="merchant"?"تاجر":r==="driver"?"سائق":"مدير"}</label>)}<button className={u.is_active?"danger":""} onClick={()=>void activeToggle(u)}>{u.is_active?"تعطيل الحساب":"تفعيل الحساب"}</button></div></article>)}</div></section>}
 {tab==="stores"&&<section><div className="psection"><div><span className="pkicker">الفروع</span><h2>{role==="admin"?"كل المتاجر":"متاجري"}</h2></div></div><div className="store-list">{stores.map(s=><div className="pstore" key={s.id}><div><b>{s.name}</b><small>{s.category} • توصيل {money(s.delivery_fee)} • حد أدنى {money(s.min_order)}</small></div><div className="store-actions"><span className={s.is_open?"open":"closed"}>{s.is_open?"مفتوح":"مغلق"}</span>{role==="admin"&&<button onClick={()=>setEditingStore({...s})}>تعديل</button>}{role==="merchant"&&<button onClick={async()=>{const {error}=await supabase.from("stores").update({is_open:!s.is_open,updated_at:new Date().toISOString()}).eq("id",s.id).eq("owner_id",session.user.id);if(error)return setToast(msg(error));await load(session.user.id)}}>{s.is_open?"إغلاق":"فتح"}</button>}</div></div>)}</div>{editingStore&&<div className="edit-card"><h3>تعديل المتجر</h3><div className="form-grid"><input value={editingStore.name} onChange={e=>setEditingStore({...editingStore,name:e.target.value})} placeholder="اسم المتجر"/><input value={editingStore.category} onChange={e=>setEditingStore({...editingStore,category:e.target.value})} placeholder="التصنيف"/><input value={editingStore.address} onChange={e=>setEditingStore({...editingStore,address:e.target.value})} placeholder="العنوان"/><input type="number" value={editingStore.delivery_fee} onChange={e=>setEditingStore({...editingStore,delivery_fee:e.target.value})} placeholder="رسوم التوصيل"/><input type="number" value={editingStore.min_order} onChange={e=>setEditingStore({...editingStore,min_order:e.target.value})} placeholder="الحد الأدنى"/><input type="number" value={editingStore.prep_minutes} onChange={e=>setEditingStore({...editingStore,prep_minutes:e.target.value})} placeholder="الدقائق"/><label><input type="checkbox" checked={editingStore.is_open} onChange={e=>setEditingStore({...editingStore,is_open:e.target.checked})}/> مفتوح</label></div><button onClick={()=>void saveStore(editingStore)}>حفظ التغييرات</button><button className="cancel-btn" onClick={()=>setEditingStore(null)}>إلغاء</button></div>}</section>}
 {tab==="menu"&&<section><div className="psection"><div><span className="pkicker">الكتالوج</span><h2>{role==="admin"?"إدارة المنيو":"منيو متجري"}</h2></div></div>{role==="admin"&&<div className="menu-tools"><select value={activeStore?.id||""} onChange={e=>setSelectedStore(e.target.value)}>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="add-row"><input value={newItem.name} onChange={e=>setNewItem({...newItem,name:e.target.value})} placeholder="اسم صنف جديد"/><input value={newItem.description} onChange={e=>setNewItem({...newItem,description:e.target.value})} placeholder="الوصف"/><input type="number" value={newItem.price} onChange={e=>setNewItem({...newItem,price:e.target.value})} placeholder="السعر"/><input value={newItem.category} onChange={e=>setNewItem({...newItem,category:e.target.value})} placeholder="التصنيف"/><button onClick={()=>void addMenu()}>إضافة</button></div></div>}{role==="merchant"&&stores.length>1&&<select value={activeStore?.id||""} onChange={e=>setSelectedStore(e.target.value)}>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}<div className="menu-table">{menus.filter(m=>!activeStore||m.store_id===activeStore.id).map(m=><div key={m.id}><div><input value={m.name} onChange={e=>setMenus(xs=>xs.map(x=>x.id===m.id?{...x,name:e.target.value}:x))}/><textarea value={m.description} onChange={e=>setMenus(xs=>xs.map(x=>x.id===m.id?{...x,description:e.target.value}:x))}/></div><input type="number" value={m.price} onChange={e=>setMenus(xs=>xs.map(x=>x.id===m.id?{...x,price:e.target.value}:x))}/><label><input type="checkbox" checked={m.is_available} onChange={e=>setMenus(xs=>xs.map(x=>x.id===m.id?{...x,is_available:e.target.checked}:x))}/> متاح</label><button onClick={()=>role==="admin"?void editMenu(m):void editMerchantMenu(m)}>حفظ</button></div>)}</div>{!menus.filter(m=>!activeStore||m.store_id===activeStore.id).length&&<div className="pempty">مفيش أصناف حاليًا.</div>}</section>}
 {tab==="applications"&&role==="admin"&&<section><div className="psection"><div><span className="pkicker">مراجعة بشرية</span><h2>طلبات التجار والسائقين</h2></div></div><h3 className="subhead">التجار</h3><div className="app-list">{merchantApps.map(a=><Application key={a.id} row={a} type="merchant" decide={adminDecision}/>)}</div><h3 className="subhead">السائقون</h3><div className="app-list">{driverApps.map(a=><Application key={a.id} row={a} type="driver" decide={adminDecision}/>)}</div>{!merchantApps.length&&!driverApps.length&&<div className="pempty">مفيش طلبات انضمام.</div>}</section>}
 {tab==="notifications"&&role==="admin"&&<section><div className="psection"><div><span className="pkicker">تنبيه وتشغيل</span><h2>إرسال إشعار</h2></div></div><div className="edit-card"><select value={notify.userId} onChange={e=>setNotify({...notify,userId:e.target.value})}><option value="">كل المستخدمين النشطين</option>{users.filter(u=>u.is_active).map(u=><option key={u.user_id} value={u.user_id}>{u.full_name||u.phone||u.user_id.slice(0,6)}</option>)}</select><input value={notify.title} onChange={e=>setNotify({...notify,title:e.target.value})} placeholder="عنوان الإشعار"/><textarea value={notify.body} onChange={e=>setNotify({...notify,body:e.target.value})} placeholder="نص الإشعار"/><button onClick={()=>void sendNotification()}>إرسال الإشعار</button></div></section>}
 {tab==="audit"&&role==="admin"&&<section><div className="psection"><div><span className="pkicker">الشفافية</span><h2>سجل الإدارة</h2></div></div><div className="audit-list">{audit.map(a=><div className="mini-row" key={a.id}><span>{new Date(a.created_at).toLocaleString("ar-EG")}</span><b>{a.action}</b><strong>{a.entity_type}</strong></div>)}</div></section>}
 {tab==="earnings"&&role==="driver"&&<section><div className="big-earning"><span>الطلبات المكتملة</span><strong>{driverDoneCount(orders,session?.user?.id)}</strong><p>كل رحلة مكتملة من حسابك تظهر هنا.</p></div></section>}
 </main>{toast&&<div className="toast">{toast}</div>}</div>;
}
function driverDoneCount(orders:Order[],uid:string){return orders.filter(o=>o.driver_id===uid&&o.status==="delivered").length}
function Stat({n,t}:{n:any;t:string}){return <div className="stat"><b>{n}</b><span>{t}</span></div>}
function Application({row,type,decide}:{row:AppRow;type:"merchant"|"driver";decide:(k:"merchant"|"driver",r:AppRow,s:"approved"|"rejected")=>void}){return <article className="app-card"><div><small>{new Date(row.created_at).toLocaleDateString("ar-EG")}</small><b>{type==="merchant"?row.business_name:row.full_name}</b><span>{row.phone} • {type==="merchant"?`${row.category} • ${row.address}`:row.vehicle_type}</span></div><div><span className={`badge ${row.status}`}>{row.status==="pending"?"قيد المراجعة":row.status==="approved"?"مقبول":"مرفوض"}</span>{row.status==="pending"&&<><button onClick={()=>decide(type,row,"approved")}>اعتماد</button><button className="reject" onClick={()=>decide(type,row,"rejected")}>رفض</button></>}</div></article>}
