import {useEffect,useState} from "react";
import {supabase} from "./lib/supabase";

type Complaint={id:string;order_id:string|null;subject:string;message:string;status:string;admin_note:string;created_at:string;updated_at:string};
type Props={admin?:boolean};
const labels:Record<string,string>={open:"مفتوحة",in_progress:"قيد المتابعة",resolved:"تم الحل",closed:"مغلقة"};
export default function SupportCenter({admin=false}:Props){
 const [session,setSession]=useState<any>(null),[rows,setRows]=useState<Complaint[]>([]),[orders,setOrders]=useState<any[]>([]),[subject,setSubject]=useState(""),[message,setMessage]=useState(""),[orderId,setOrderId]=useState(""),[busy,setBusy]=useState(false),[toast,setToast]=useState<string|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)void load(data.session.user.id)})},[]);
 async function load(uid:string){setBusy(true);try{if(admin){const {data}=await supabase.from("complaints").select("*").order("created_at",{ascending:false}).limit(200);setRows(data||[])}else{const [c,o]=await Promise.all([supabase.from("complaints").select("*").eq("customer_id",uid).order("created_at",{ascending:false}),supabase.from("orders").select("id,created_at,stores(name)").eq("customer_id",uid).order("created_at",{ascending:false}).limit(50)]);setRows(c.data||[]);setOrders(o.data||[])}}finally{setBusy(false)}}
 async function submit(){if(!session)return setToast("سجّل الدخول الأول");if(!subject.trim()||!message.trim())return setToast("اكتب الموضوع والرسالة");setBusy(true);const {error}=await supabase.rpc("submit_complaint",{p_order_id:orderId||null,p_subject:subject.trim(),p_message:message.trim()});setBusy(false);if(error)return setToast(error.message);setSubject("");setMessage("");setOrderId("");setToast("الشكوى اتبعت ✓");void load(session.user.id)}
 async function update(row:Complaint,status:string){const {data,error}=await supabase.rpc("admin_set_complaint",{p_id:row.id,p_status:status,p_admin_note:row.admin_note||""});if(error)return setToast(error.message);setRows(xs=>xs.map(x=>x.id===row.id?data:x));setToast("تم تحديث الشكوى ✓")}
 return <div className="page inner" dir="rtl"><div className="title"><div><span className="kicker">الدعم</span><h1>{admin?"إدارة الشكاوى":"مساعدة ودعم"}</h1></div><button className="outline" onClick={()=>history.back()}>رجوع</button></div>{!admin&&<section className="section"><div className="edit-card"><h2>ابعتلنا المشكلة</h2><select value={orderId} onChange={e=>setOrderId(e.target.value)}><option value="">من غير طلب محدد</option>{orders.map(o=><option key={o.id} value={o.id}>طلب #{o.id.slice(0,6).toUpperCase()} • {o.stores?.name||"متجر"}</option>)}</select><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="موضوع المشكلة"/><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="اشرح المشكلة بالتفصيل" rows={6}/><button className="primary full" disabled={busy} onClick={()=>void submit()}>إرسال الشكوى</button></div></section>}<section className="section"><div className="section-head"><div><span className="kicker">المتابعة</span><h2>{admin?"كل الشكاوى":"شكاواي"}</h2></div><button className="refresh" onClick={()=>session&&void load(session.user.id)}>تحديث ↻</button></div>{rows.length?rows.map(r=><article className="order" key={r.id}><div className="order-head"><div><small>#{r.id.slice(0,6).toUpperCase()} • {new Date(r.created_at).toLocaleString("ar-EG")}</small><h3>{r.subject}</h3><p>{r.message}</p>{r.order_id&&<small>الطلب: #{r.order_id.slice(0,6).toUpperCase()}</small>}{r.admin_note&&<p>ملاحظة الإدارة: {r.admin_note}</p>}</div><span>{labels[r.status]||r.status}</span></div>{admin&&<div className="order-foot"><select value={r.status} onChange={e=>void update(r,e.target.value)}>{Object.keys(labels).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div>}</article>):<div className="empty"><div>🛟</div><h3>{busy?"جاري التحميل…":"مفيش شكاوى"}</h3><p>{admin?"أي شكوى جديدة هتظهر هنا.":"لو قابلتك مشكلة ابعتها من النموذج فوق."}</p></div>}</section>{toast&&<div className="toast">{toast}</div>}</div>;
}
